### ISSUE TITLE
Bug: Undefined constant "CodeIgniter\Database\MySQLi\MYSQLI_STORE_RESULT"

### ISSUE THREAD

**Issue by blipur** [codeigniter4/shield#1009]
### PHP Version

8.3.2

### CodeIgniter4 Version

4.4.5

### Shield Version

1.0

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

cli-server (PHP built-in webserver)

### Database

MySQL 8.0.36

### Did you customize Shield?

No

### What happened?

After I'm install shield from documentation https://shield.codeigniter.com/getting_started/install/, and after I'm run, show massage Undefined constant "CodeIgniter\Database\MySQLi\MYSQLI_STORE_RESULT", before install shield it's normally.

I'm can run migration from cli, and ext mysqli already install in php

### Steps to Reproduce

I use this php
![image](https://github.com/codeigniter4/shield/assets/62276883/8141b795-6fd4-4827-8f72-4951cfe2d602)
and no apache

![image](https://github.com/codeigniter4/shield/assets/62276883/8abfb3c8-5c09-475f-876f-677d766b604e)
i'm run using spark

run php -m
======
[PHP Modules]
bcmath
calendar
Core
ctype
curl
date
dom
fileinfo
filter
hash
iconv
intl
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcre
PDO
pdo_mysql
pdo_pgsql
pdo_sqlite
Phar
random
readline
Reflection
session
SimpleXML
SPL
sqlite3
standard
tokenizer
xml
xmlreader
xmlwriter
Zend OPcache
zlib

[Zend Modules]
Zend OPcache

![image](https://github.com/codeigniter4/shield/assets/62276883/45a4646b-d650-4681-abf2-c3bd6f489421)

### Expected Output

![image](https://github.com/codeigniter4/shield/assets/62276883/8c005273-fd1b-4e89-b27f-79862061a209)

**Comment by samsonasik** [comment]
You seems have different ext enabled for web vs cli, ensure that on web env, the mysql* extension installed.

**Comment by blipur** [comment]
hai, i'm again, my problem is solve, i reinstall my vendor using composer install, before that, i remove my vendor folder. thanks four your supports

**Comment by kenjis** [comment]
Good to hear.

If you think it is a bug, it is okay to create an issue.
But if you don't know it is a bug or not, please use the Discussion:
https://github.com/codeigniter4/shield/discussions/categories/q-a
