### ISSUE TITLE
Bug: Bearer prefix on auth header (JWT Authenticator)

### ISSUE THREAD

**Issue by MrFrost-Nv27** [codeigniter4/shield#1038]
### PHP Version

8.2.1

### CodeIgniter4 Version

4.2.5

### Shield Version

1.0.1

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

MySQL

### Did you customize Shield?

Yes, on JWT Authenticator is not same as JWT Filter on grab the token, JWT Filter was done with bearer prefix but in JWT Authenticator wasn't, please see my change below
![Screenshot 2024-02-22 110240](https://github.com/codeigniter4/shield/assets/70581926/26dc4bb0-617c-4975-a914-196dea12ae79)

### What happened?

error malformed loggedIn method on JWT Authenticator because the method for grab the token isn't fixed with bearer prefix
![Screenshot 2024-02-22 110456](https://github.com/codeigniter4/shield/assets/70581926/96baa3a5-2bf0-49eb-9711-7d004be4a314)

### Steps to Reproduce

add getTokenFromHeader method like JWT Filter in JWT Authenticator

### Expected Output

easyly doing prefix or not on loggedin method with JWT Authenticator

### Anything else?

nothing, just see my opinion and do update if it good

**Comment by kenjis** [comment]
Thank you for reporting.
I can't see the changes in the screenshot, can you send a Pull Request?

**Comment by MrFrost-Nv27** [comment]
okay, this my pull request #1039

**Comment by kenjis** [comment]
Thank you for the PR!
I refactored it a bit. See #1040
If it is okay, please approve it.

**Comment by MrFrost-Nv27** [comment]
> Thank you for the PR! I refactored it a bit. See #1040 If it is okay, please approve it.

Yes that good
