### ISSUE TITLE
What is the difference between Event `didLogin` and `login` ?

### ISSUE THREAD

**Issue by kenjis** [codeigniter4/shield#105]
> `didLogin`
> Fired immediately after a successful login. The only argument is the User entity.
https://github.com/codeigniter4/shield/blob/develop/docs/5%20-%20events.md#didlogin

> Modules that handle login and logout operations should trigger the `login` and `logout` Events when successful
https://codeigniter4.github.io/CodeIgniter4/extending/authentication.html#recommendations

Related: #99

**Comment by MGatner** [comment]
I'm not sure where "didLogin" came from, probably an addition by @lonnieezell

**Comment by kenjis** [comment]
When is a successful login?
In case of 2FA, the authentication flow is the following:
1. Post "ID/Password" -> check OK
2. Post "Email Address" -> send email
3. Post "Auth Token" -> check OK

True login seems to be 3. 
Should the login event be triggered both 1. and 3. ?

**Comment by lonnieezell** [comment]
I think the original intent was that `didLogin` would be an after login and there was going to be a before login. I think I decided that having both wasn't really needed and intended to standardize to just `login` but never removed that one. 

My thinking about when it was fired is that you're not successfully logged in and able to do anything until you've authenticated so it should be after 2FA. Doing it in two places could be problematic for listeners on the event that do something twice, like sending duplicated emails, etc.

**Comment by kenjis** [comment]
When we use 2FA, the `login` is fired only after 3.
When we don't use 2FA, the `login` is fired after 1.

Is this okay?

**Comment by lonnieezell** [comment]
Yes, I think that is good.

**Comment by kenjis** [comment]
I sent a PR to fix: #126

and thanks for the explanation of `didLogin`.

**Comment by MGatner** [comment]
I agree with this behavior. Thanks for fixing kenjis
