### ISSUE TITLE
Bug: [CI 4.5.0] TypeError: CodeIgniter\Database\MySQLi\Connection::_escapeString(): Argument #1 ($str) must be of type string, CodeIgniter\I18n\Time given

### ISSUE THREAD

**Issue by jlopes90** [codeigniter4/shield#1092]
### PHP Version

8.1

### CodeIgniter4 Version

4.5.0

### Shield Version

dev-develop

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

MySQL 5.6

### Did you customize Shield?

No.

### What happened?

When logging in and an error appears.

![image](https://github.com/codeigniter4/shield/assets/50026015/891761f3-55c9-48ea-9b8d-7d79fdde170a)

### Steps to Reproduce

...

### Expected Output

...

**Comment by datamweb** [comment]
We are aware of this behavior. But so far no decision has been made to fix it. I believe this is related to CI4.5 and not Shield.
For now, the **temporary solution** is as follows:

**vendor\codeigniter4\framework\system\Database\BaseConnection.php**:

```php
    /**
     * Platform independent string escape.
     *
     * Will likely be overridden in child classes.
     */
    protected function _escapeString(string|\CodeIgniter\I18n\Time $str): string
    {
        return str_replace("'", "''", remove_invisible_characters($str, false));
    }
```

**vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php**:

```php
    /**
     * Platform-dependant string escape
     */
    protected function _escapeString(string|\CodeIgniter\I18n\Time $str): string
    {
        if (! $this->connID) {
            $this->initialize();
        }

        return $this->connID->real_escape_string((string)$str);
    }
```
duplicate: #1086

**Comment by ay4t** [comment]
me too i got same error, Has this been updated in the release version?

**Comment by samsonasik** [comment]
CodeIgniter 4.5.1 already released, please update and verify

**Comment by warcooft** [comment]
> me too i got same error, Has this been updated in the release version?

Update ke CI 4.5.1
Tapi ada sedikit bug di validasi shield, ditunggu aja update minor nya.

**Comment by ay4t** [comment]
> > me too i got same error, Has this been updated in the release version?
> 
> Update ke CI 4.5.1 Tapi ada sedikit bug di validasi shield, ditunggu aja update minor nya.

makasi bang infonya

**Comment by kenjis** [comment]
Upgrade to CI v4.5.1 and Shield v1.0.3.
