### ISSUE TITLE
Bug: [CI 4.5.0] Call to a member function getErrors() on null

### ISSUE THREAD

**Issue by iamsyh** [codeigniter4/shield#1093]
### PHP Version

8.2.17

### CodeIgniter4 Version

4.5.0

### Shield Version

1.0.2

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### Database

Mysql 8

### Did you customize Shield?

No

### What happened?

When logging in an error appears.

![Screenshot 2024-04-09 at 03-17-28 Error](https://github.com/codeigniter4/shield/assets/5077021/6d859e7d-5a5e-403e-8819-18ccb038c0d8)

### Steps to Reproduce

..

### Expected Output

..

**Comment by datamweb** [comment]
It has already been resolved. #1088
