### ISSUE TITLE
Bug: VENDORPATH/codeigniter4/shield/src/Models/CheckQueryReturnTrait.php at line 44

### ISSUE THREAD

**Issue by rjwmtgevolution** [codeigniter4/shield#1096]
### PHP Version

8.2

### CodeIgniter4 Version

4.5.0

### Shield Version

1.0

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### Database

postgresql

### Did you customize Shield?

no

### What happened?

composer update to 4.5.0. I went to login and got the following error

I believe this is going to Call to a member function getErrors() on null

VENDORPATH/codeigniter4/shield/src/Models/CheckQueryReturnTrait.php at line 44

### Steps to Reproduce

the project was on codeigniter 4.4.7 and then I composer updated to 4.5.0 this morning

### Expected Output

be able to login

**Comment by datamweb** [comment]
This bug has already been fixed(see #1088). Note that Shield is not currently compatible with version 4.5.
Good work done for compatibility. You should also wait for a new version of the CI framework(maybe 4.5.1) to be released.

**Comment by rjwmtgevolution** [comment]
thank you, I appreciate the quick response. 

I updated the shield code and that fixed that issue. 

I am getting  another error now, after logging in. I click on the back button and I end up logged in.

pg_escape_literal(): Argument #2 ($string) must be of type string, CodeIgniter\I18n\Time given

SYSTEMPATH/Database/Postgre/Connection.php at line 242

**Comment by datamweb** [comment]
You will need the following:
https://github.com/codeigniter4/CodeIgniter4/pull/8739
https://github.com/codeigniter4/CodeIgniter4/pull/8738
#1095

**Comment by rjwmtgevolution** [comment]
Thank you for the update. 

I am not sure what to do to put the fix in place. 

I clicked on the links to review but I am not sure what to do to fix the problem. 

Sorry for my ignorance.

**Comment by rjwmtgevolution** [comment]
sorry, I see the update / fix on issue 

https://github.com/codeigniter4/shield/issues/1092

**Comment by rjwmtgevolution** [comment]
I am able to login now.

Thank you for your help.

**Comment by datamweb** [comment]
> I clicked on the links to review but I am not sure what to do to fix the problem.

Select tab "Files changed".
Then you will see all the files that have changed. You should apply these changes in each of your project files.

![Screenshot 2024-04-09 225049](https://github.com/codeigniter4/shield/assets/9530214/d2a716f4-efbf-4bde-b23e-8e989c532c0e)


> I am able to login now.

Do not forget that this is not a fundamental solution. Use the new version as soon as it is released.

**Comment by rjwmtgevolution** [comment]
perfect, thank you
