### ISSUE TITLE
Bug: Error Occurred While Changing User Password: strtolower(): Argument #1 ($string) must be of type string, null given in NothingPersonalValidator

### ISSUE THREAD

**Issue by arashsaffari** [codeigniter4/shield#1171]
### PHP Version

8.3.10

### CodeIgniter4 Version

4.5.4

### Shield Version

1.1.0

### Which operating systems have you tested for this bug?

macOS

### Which server did you use?

apache

### Database

MySQL 8

### Did you customize Shield?

Yes, but I believe my changes have nothing to do with the error.

### What happened?

When changing a user's password, I encounter the following error:
```
strtolower(): Argument #1 ($string) must be of type string, null given
```

This error is caused by the NothingPersonalValidator.

### Steps to Reproduce

```php
if (! $this->validate($userValidationRules))
{
return redirect()->to('/users/update/' . $id)->withInput()->with('errors', $this->validator->getErrors());
}
```

### Expected Output

<img width="1239" alt="Bildschirmfoto 2024-08-18 um 03 22 27" src="https://github.com/user-attachments/assets/0de8bbcc-afee-43d6-acb9-14a9e7d702d8">

**Comment by warcooft** [comment]
Can you show the complete code?

it looks like the email is missing or it could be that you create username only as your login credentials instead of using email.

**Comment by datamweb** [comment]
Hey @arashsaffari ,

In Shield, all users are required to have a unique email address, which is mandatory during the registration process. However, it's possible to log in using other identifiers besides email, such as a username, employee ID, etc.

Considering this, it seems that the user you're trying to change the password for does not have an email address associated with their account.

Please verify that the user has an email by running the following command:

```console
php spark db:table auth_identities
```

Ensure that the user has a valid email (field **secret**).

If the user does have an email and the problem persists, please provide the minimal code necessary to reproduce the error.

**Comment by arashsaffari** [comment]
I have an email address stored in the database. The problem is that when using `$user->email`, the `getEmail()` function in the User entity is not being called. However, when I call the `$user->getEmail()` function in the controller, `$user->email` is populated with the email address. Interestingly, when I work with `$user->password_hash`, the `getPasswordHash()` function in the entity is called, and I receive the hash. It's worth noting that I have the email stored in my `auth_identities` table, and my login credentials use instead of the email.

**Comment by warcooft** [comment]
Can you show the code how you call the user data? if you call it correctly then the email displays well.

For example:
```php

$usersModel = auth()->getProvider();
//find user where id is "7"
$user = $usersModel->find(7);
//show user email
dd($user->email); // result "example@pointerpointer.com"
```

**Comment by kenjis** [comment]
It appears that you have written incorrect code regarding `User`.

**Comment by warcooft** [comment]
I can reproduce a similar error.

in my case, I added a personal field to `$personalFields` where the type of the field or its value is an `integer`. To prevent this error, we should cast the personal field value to a string.

**Comment by warcooft** [comment]
> I can reproduce the error in this issue.
> 
> It seems you added a personal field to `$personalFields` where the type of the field or its value is an `integer`. To prevent this error, we should cast the personal field value to a string.

In my case, it’s specifically related to `$personalFields`, so this situation is different.

**Comment by datamweb** [comment]
We did not receive the minimum code required to reproduce the issue. This issue is now closed.
