### ISSUE TITLE
remember-me cookie is always not secure

### ISSUE THREAD

**Issue by kenjis** [codeigniter4/shield#120]
https://github.com/codeigniter4/shield/blob/a76b35e7bf6746037b94061fab08cfcd08ac89b5/src/Authentication/Authenticators/Session.php#L334

**Comment by lonnieezell** [comment]
I don't believe we can force this true currently. While all sites should be secure, we can't know what everyone's environment will be, especially during development. However, a config setting could be used to define this.

**Comment by kenjis** [comment]
Yes, we need a config setting,

**Comment by lonnieezell** [comment]
Actually - I think we can do: 

```php
service('request')->isSecure();
```

**Comment by kenjis** [comment]
If the site enforces HTTPS, it would be okay.
But if the site accepts both HTTP/HTTPS, then an attacker may lead a victim to HTTP connection.

**Comment by lonnieezell** [comment]
They would also be seeing other errors with javascript if they were doing mixed http/https. My thinking is that I would hope that's a rare situation and basing it on whether the request is secure or not is more likely to be secure than hoping developers remember to change the setting when they go live.

**Comment by kenjis** [comment]
This is CI4 package. Why don't we use the CI4 Cookie config?

**Comment by lonnieezell** [comment]
I think that works for now.
