### ISSUE TITLE
We need better language to express `login`

### ISSUE THREAD

**Issue by kenjis** [codeigniter4/shield#128]
2FA gives two meanings in the word `login`.

The default Email/Password authentication:
Sending Email/Password and they are matched, `login` is completed.

2FA:
(1) sending Email/Password and they are matched, and
(2) sending Token and it is matched, `login` is completed.

We have no words to describe the user status (1).

On the other hand,
we have the `Session::login()` method to log the given user in. 
But when using 2FA, the `login` is not completed after calling the method.

This is confusing.

**Comment by MGatner** [comment]
IMO the term "login" should denote once authentication is complete, i.e. the user has no further Auth steps to take. 

Correct me if I am wrong, but there is no "server state" after the email is sent but before the token is exchanged, right? Why do we need to define that limbo?

**Comment by MGatner** [comment]
Ohhh, no, I see I was wrong: Session has to record the user prior to Email2FA completing the verification. The thread on the other PR makes a lot more sense now 😅

Here's my opinion: I don't think `auth()->user()` should not return a User until `login` is complete. For 2FA this means "after token verification". This means either:
1. Using an intermediate session state to define a "pending" login
2. Or using an actual token that is only created once credentials pass (this is probably less secure since intercepting the token would allow anyone to login)

**Comment by kenjis** [comment]
Yes, the current implementation is based on 1FA and the `login` concept does not match 2FA.
`auth()->user()` returns a "pending" login User.
`Session::login()` does not complete the login, so it makes a User "pending" login state.

**Comment by kenjis** [comment]
The `login` event should be fired or not when registration process is completed?

> I don't think login event should be fired during registration.
https://github.com/codeigniter4/shield/pull/126#discussion_r872918103

> Same thing applies to the email activation process. Users are automatically logged in to the application after verifying their email address. The didLogin event should also be fired. https://github.com/codeigniter4/shield/pull/99

**Comment by MGatner** [comment]
My opinion: anything that results in an authenticated user should trigger `login`. This is how I expect developers to use this event so if we allow some scenarios where that isn't true it could be very confusing. Other events that happen to result in an authenticated user, like registration, should either trigger `login` (plus their own event) or be changed so the user is not authenticated (i.e. register first, then use the new credentials to login from the form).

**Comment by lonnieezell** [comment]
I think a "pending" state would be an accurate addition here.

**Comment by kenjis** [comment]
> anything that results in an authenticated user should trigger login.

We need to discuss about it.
See #131

**Comment by kenjis** [comment]
> auth()->user() returns a "pending" login User.


PR #132 will change it.

**Comment by kenjis** [comment]
What should the login() method do?
Currently, it is not clear what this method does.

https://github.com/codeigniter4/shield/blob/d136ff7e3c4341e35a2559e43ca29e5fe5640114/src/Authentication/Authenticators/Session.php#L335-L338

**Comment by lonnieezell** [comment]
Do you still have questions on this? Or did you get it cleared up while going through your other PR? 

Basically - it does any session maintenance needed for security, sets a value in the session we can check to see if they're logged in, stores an instance of the user object so it can be retrieved from `auth()->user()` and sets a remember token for the user if they need it.

**Comment by kenjis** [comment]
I still have my doubts about whether the current `login()` method (my other PR does not change it) is the right one.

**Comment by lonnieezell** [comment]
What are your concerns with it?

**Comment by kenjis** [comment]
The `login()` method may not complete the login. It cannot guarantee that the login is completed.

The pending login state depends on whether the identity for the action is stored in the DB.
But the `login()` does not care about pending state now.

**Comment by kenjis** [comment]
I noticed that the value of the session variable does not accurately represent the current state. 
Right now we can't know if it is pending login or not from the session value.
I think it should be fixed.

And if we fix it, we might be able to refactor the code to be more concise depending on the session variable.

**Comment by lonnieezell** [comment]
I believe this has been fixed now. Can we close this @kenjis ?
