### ISSUE TITLE
Table `auth_activation_attempts` is not used

### ISSUE THREAD

**Issue by kenjis** [codeigniter4/shield#138]
We have `EmailActivator`, so we should use the table for it?

But the table has the following:
```php
        [
            'id'         => ['type' => 'int', 'constraint' => 11, 'unsigned' => true, 'auto_increment' => true],
            'ip_address' => ['type' => 'varchar', 'constraint' => 255],
            'user_agent' => ['type' => 'varchar', 'constraint' => 255],
            'token'      => ['type' => 'varchar', 'constraint' => 255, 'null' => true],
            'created_at' => ['type' => 'datetime', 'null' => false],
        ]
```

On the other hand, `auth_logins` has the following:
```php
        [
            'id'         => ['type' => 'int', 'constraint' => 11, 'unsigned' => true, 'auto_increment' => true],
            'ip_address' => ['type' => 'varchar', 'constraint' => 255, 'null' => true],
            'user_agent' => ['type' => 'varchar', 'constraint' => 255, 'null' => true],
            'email'      => ['type' => 'varchar', 'constraint' => 255, 'null' => true],
            'user_id'    => ['type' => 'int', 'constraint' => 11, 'unsigned' => true, 'null' => true], // Only for successful logins
            'date'       => ['type' => 'datetime'],
            'success'    => ['type' => 'tinyint', 'constraint' => 1],
        ]
```

It seems `auth_activation_attempts` needs `user_id` and `success`.

**Comment by MGatner** [comment]
Let's hold until #131.

**Comment by lonnieezell** [comment]
That was a remnant from Myth:Auth's tables, I think. And definitely from before I switched to using identities, which is probably where it got dropped. 

I think it probably would be good to log those attempts, though, in order to trace attempted hacks if needed. Adding user_id and success is fine by me.

**Comment by kenjis** [comment]
> I think it probably would be good to log those attempts, though, in order to trace attempted hacks if needed. Adding user_id and success is fine by me.

Yes. But for now I sent a PR to remove this table.

We should log not only activation attempts but also 2FA code post attempts.
