### ISSUE TITLE
`auth_logins.email` is not only email

### ISSUE THREAD

**Issue by kenjis** [codeigniter4/shield#139]
It is confusing.

https://github.com/codeigniter4/shield/blob/836723c1401d786c256d8d2cb90d9f24776df65c/src/Authentication/Authenticators/AccessTokens.php#L51

https://github.com/codeigniter4/shield/blob/836723c1401d786c256d8d2cb90d9f24776df65c/src/Models/LoginModel.php#L42

**Comment by MGatner** [comment]
Oh yeah that's unfortunate. Maybe we should rename it `secret` like the identities table? It's possible this might record more, pending decisions in #131

**Comment by lonnieezell** [comment]
I think maybe renaming it to `identifier` might be a better name than `secret`.

**Comment by kenjis** [comment]
Yes, `identifier` is better. It might be email, username, token.

**Comment by kenjis** [comment]
By the way, what value should be returned by `User::lastLogin()`?
What is the last login?

Now it returns the last `email` login.
https://github.com/codeigniter4/shield/blob/cd1f41ee63471b8957353ad1912cc1590f7c4b75/src/Entities/User.php#L183-L187

**Comment by lonnieezell** [comment]
It returns the db record of the last login attempt.
