### ISSUE TITLE
Use email only for login/registration

### ISSUE THREAD

**Issue by KipchirchirIan** [codeigniter4/shield#144]
I need to use just the email for login/registration. What are the steps to configure or setup this?

**Comment by kenjis** [comment]
I've not tried, but how about this?

1. remove `username` in the config.
https://github.com/codeigniter4/shield/blob/44901bcd27d4f87535126de426a361182ad67775/src/Config/Auth.php#L216-L223
2. remove `username` in the HTML form in `src/Views/register.php`.
3. remove `username` validation rule in `RegisterController`.
4. customize the login form.

**Comment by lonnieezell** [comment]
Yes, the steps that @kenjis provided will work for you. You should probably copy the views and controller to your application, though.
