### ISSUE TITLE
Login/registration error after update

### ISSUE THREAD

**Issue by sammyskills** [codeigniter4/shield#150]
Hi,

I recently updated to the most recent version and when I try to login or register an account, I get the following error:

`mysqli_sql_exception #1064`
`You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 4`.

When I check the database after registration, I see the records being inserted/updated. But the page dies almost immediately with the above error.

Where can I check ?

**Comment by lonnieezell** [comment]
I'm not 100% this was the fix, but I hit that 2 nights ago while working on the code. I believe it's that we changed a field name in the `auth_logins` table. Try changing the name of `email` to `identifier` and let me know if that solves it.

**Comment by jozefrebjak** [comment]
@lonnieezell I have the same issue, fresh install. I already have `identifier` in `auth_logins` table and there is same issue even with suggested change.

**Comment by lonnieezell** [comment]
Hm. I'll take a look tonight. That should be pulling the information from the Auth config file. I can see that being an issue with an existing install but not from a new install.

**Comment by kenjis** [comment]
It seems it is a SQL syntax error.
What SQL statement is causing the error?

**Comment by MGatner** [comment]
@sammyskills Try #151

**Comment by lonnieezell** [comment]
Oops -

**Comment by jozefrebjak** [comment]
@lonnieezell after update with PR #151 I can login successfully.

**Comment by sammyskills** [comment]
Works fine after PR #151 update. 

Thank you.
