### ISSUE TITLE
User::lastLogin() does not return login data that logged in by username/password

### ISSUE THREAD

**Issue by kenjis** [codeigniter4/shield#155]
https://github.com/codeigniter4/shield/blob/e92712645e19ca6ce9db54bc4065d51fbebdb7f2/src/Entities/User.php#L187-L200

**Comment by MGatner** [comment]
I don't understand the problem, but this might be a note to yourself anyway.

**Comment by kenjis** [comment]
When username/password (not email/password) login can be used, the `identifier` is the username.
https://github.com/codeigniter4/shield/blob/0cd72f8cce31611e4b8adffa129a4485aeaa3f2c/src/Authentication/Authenticators/Session.php#L231-L237

But the `where` in the method specifies email.
https://github.com/codeigniter4/shield/blob/e92712645e19ca6ce9db54bc4065d51fbebdb7f2/src/Entities/User.php#L197

**Comment by MGatner** [comment]
Ohhh right, thanks for explaining.

**Comment by MGatner** [comment]
Probably a `orWhere` would fix this, but it brings up the question: what if developers store their own identifiers? Do we need a more comprehensive mapping from User identities to attempts?

**Comment by kenjis** [comment]
It seems we should argue the use case of the method.
What is the method for?

It seems the table records all login attempts (password/magic link/access token) success/failed.

**Comment by MGatner** [comment]
A good question for @lonnieezell! It isn't used internally but I'm guessing it is to make it easy to display "Last login _____". Maybe the "failed" option was going to be part of the "limit failure attempts" feature that we recently dropped?

**Comment by MGatner** [comment]
All good points. Here's what I think: we remove the "failed" aspect and just makes this return the last successful by `user_id`. If we want a second method to return failures, make it accept an identifier and type so the developer knows what they are getting ahead of time.

**Comment by kenjis** [comment]
> The table records all attempts to login not just for last login ... it also provides a history of attempts so if a bot or hacker is attempting to login it can be tracked.

Okay, it is the purpose for the table. Both success and failure attempts should be recorded.

I think it is better not to record Access Token login in the table.
It is a kind of access log and users probably don't think it is their *login*.
Another table for Access Token login (e.g. `auth_token_logins`) would be needed.

If `auth_logins` records only Session Auth logins, finding by `user_id` can return the last login.
If so, the table name should be `auth_session_logins`?

**Comment by lonnieezell** [comment]
I don't think it's important to rename the table. Other handlers could reused the table.

**Comment by kenjis** [comment]
> So, you're correct that if their primary identifier is changed then we cannot track them, and I don't think there's a way around that. 

To display "Last login _____", only successful logins are needed.
So these records have `user_id`. Therefore finding by `user_id` in Session Auth logins is okay.
`user_id` is never changed.

If you like one logins table, how about adding a column to record handler?

**Comment by kenjis** [comment]
I don't think Access Token logins are included in the user's definition of a login.
Access Token logins do not fire the login event.

I still think it would be better to keep the tables separate as the concepts are a bit different.

**Comment by lonnieezell** [comment]
I am ok with that. We might think about a config setting on whether to track that or not, with it set to track by default.

**Comment by kenjis** [comment]
Then how about these tables?

`auth_logins`: record login attempts. A login means users think it is a login. To login, users do action(s) like posting a form.
`auth_token_logins`: record Bearer Token type login attempts. Now it records login attempts by Access Token Authenticator.

**Comment by lonnieezell** [comment]
That sounds good to me.

**Comment by MGatner** [comment]
PR looks good. Back to this discussion, I still think we should split this method out. `lastLogin()` as a name does not seem to me that it would ever return "last failed attempt using my email/username", nor do I see a scenario where that would be useful from the Entity. 

If we drop the "failed" flag this can use `user_id` and then changed identifiers won't affect it. If we really want the "failed" option we can make it a separate method that takes the appropriate parameters so as to be clear what you are getting.

**Comment by datamweb** [comment]
> If we drop the "**failed**" flag

I think this is necessary and useful.

**Comment by kenjis** [comment]
@datamweb When a developer would use `$user->lastLogin(tue)`?
For what?

**Comment by kenjis** [comment]
Events is a core functionality of CI4.
The file is `app/Config/Events.php`. You already have it if you installed CI4.

We are discussing `User::lastLogin()`, not the event `failedLogin`.
https://github.com/codeigniter4/shield/blob/7005aa568dd5e63093f3e78e5bdead663d1f4c68/src/Entities/User.php#L230
It is a method to get the last login attempt (log) from the database.
