### ISSUE TITLE
Composer Installation Not working

### ISSUE THREAD

**Issue by vimkaf** [codeigniter4/shield#157]
Running composer require codeigniter4/shield throws 
 ` Could not find a version of package codeigniter4/shield matching your minimum-stability (stable). Require it with an expli  
  cit version constraint allowing its desired stability.`

Is shield ready for production use and what is the stable version?

**Comment by datamweb** [comment]
Hi, for now, use the following command.
`composer require codeigniter4/shield:dev-develop`

**Comment by lonnieezell** [comment]
Since there hasn't been a release yet, there is no stable version. We're very close to a release, though. 

For now, I would add these lines to your composer.json: 

```
"minimum-stability": "dev",
"prefer-stable": true,
```

**Comment by vimkaf** [comment]
Working now. looking forward to a release. Thanks for all the work you do.
