### ISSUE TITLE
CodeIgniter\Shield\Auth::$user is not used anywhere

### ISSUE THREAD

**Issue by pjsde** [codeigniter4/shield#183]
`CodeIgniter\Shield\Auth::$user` is not used anywhere, so does it be necessary? or should refactor the method `Auth->user()` as follow:

```php
public function user(): ?User
{
    if ($this->user !== null) {
        return $this->user;
    }

    return $this->getAuthenticator()->loggedIn()
        ? $this->user = $this->getAuthenticator()->getUser()
        : null;
}
```

If you agree, i can make a PR with this.

**Comment by kenjis** [comment]
Once the a user is authenticated, it seems it will not be changed.
So it seems caching the user in `Auth::$user` makes sense.

@lonnieezell Your opinion?

**Comment by MGatner** [comment]
This would be duplicating our cached user since it is already stored in the Authenticator. It should just be a reference so that's technically fine but I find it confusing and potentially disruptive for tests where one might want to mock or inject a user. I would be in favor of removing the property here and leaving the method as is.

**Comment by pjsde** [comment]
@MGatner I understand what you are saying but if we check `Auth::$user` besides being affected here it is also being affected in the `Auth::authenticate()` method and it comes from the authenticator, so the origin is always the same, comes from the authenticator, so I don't think it's disruptive.

Otherwise I don't see the need for the `Auth::$user` property as it is not used anywhere, it is only written in the `Auth::authenticate()` method and has no read access, so it should be removed from the `CodeIgniter\Shield\Auth` class.

**Comment by MGatner** [comment]
Ah, thank you - I missed that it was set in `authenticate()`. I think that is equally confusing and stick to my original opinion: drop it from this class altogether.

**Comment by lonnieezell** [comment]
I think we get rid of that property. It's not used anywhere in the class. Any calls to get the user are in the authenticator class.

**Comment by pjsde** [comment]
Ok. I will submit a PR with that change
