### ISSUE TITLE
Config/Auth::$userProvider error

### ISSUE THREAD

**Issue by sammyskills** [codeigniter4/shield#200]
Hi, good people,

I have the latest copy of this library and I decided to take it for a spin, but it returned some errors while trying to run a migration or ```php spark serve```. Please find the error below:

```
Fatal error: Type of Config\Auth::$userProvider must be ?CodeIgniter\Shield\Models\UserModel (as in class CodeIgniter\Shield\Auth)
```

I followed the installation instruction in the docs by copying the Auth and AuthGroup files from the vendor folder into the ```app/Config``` folder.

**Comment by datamweb** [comment]
@sammyskills I think you did not do well in installing it. I have now installed the latest version without this problem.

![Screenshot 2022-06-03 040026](https://user-images.githubusercontent.com/9530214/171761880-a4e669b9-8a8f-44d8-98e6-7e849615c528.jpg)

**Comment by kenjis** [comment]
@sammyskills Check the value of `Config\Auth::$userProvider`.

**Comment by sammyskills** [comment]
The ```$userProvider = 'CodeIgniter\Shield\Models\UserModel'``` .

I just copied the Auth and AuthGroups files from the src folder and pasted in my app/Config folder, just as suggested in the docs, and I have updated the namespace and extended the src class.

**Comment by datamweb** [comment]
@sammyskills  Please add the values in file `app/Config/Auth.php` as follows:
```
<?php

namespace Config;

use CodeIgniter\Config\BaseConfig;
use CodeIgniter\Shield\Authentication\Actions\ActionInterface;
use CodeIgniter\Shield\Authentication\AuthenticatorInterface;
use CodeIgniter\Shield\Authentication\Authenticators\AccessTokens;
use CodeIgniter\Shield\Authentication\Authenticators\Session;
use CodeIgniter\Shield\Authentication\Passwords\ValidatorInterface;
use CodeIgniter\Shield\Models\UserModel;
use CodeIgniter\Shield\Config\Auth as ShieldAuth;

class Auth extends ShieldAuth
{
.
.
.
```

Was the problem fixed?

**Comment by kenjis** [comment]
Ah, this error message is strange. The type of `Config\Auth::$userProvider` is string, not `UserModel`.

> Fatal error: Type of Config\Auth::$userProvider must be ?CodeIgniter\Shield\Models\UserModel (as in class CodeIgniter\Shield\Auth)

Can you show back trace?

**Comment by sammyskills** [comment]
I couldn't serve up the page to get the back trace as ```php spark serve``` returned the same error.

**Comment by sammyskills** [comment]
And @datamweb , I have the exact values in my app/Config/Auth.php file.

**Comment by kenjis** [comment]
Now the latest `develop` branch has `shield:setup` command.
https://github.com/codeigniter4/shield/blob/develop/docs/0%20-%20install.md#command-setup

If you don't resolve this issue, feel free to reopen.

**Comment by sammyskills** [comment]
Oh, sorry for the delay. 
Issue is resolved indeed.

Thanks.
