### ISSUE TITLE
Erro in composer install

### ISSUE THREAD

**Issue by caosdp-rs** [codeigniter4/shield#207]
composer require codeigniter4/shield

In PackageDiscoveryTrait.php line 327:
                                                                                                                                                                                    
  Could not find a version of package codeigniter4/shield matching your minimum-stability (stable). Require it with an explicit version constraint allowing its desired stability.

**Comment by datamweb** [comment]
Hello, @caosdp-rs please see #157 .

**Comment by caosdp-rs** [comment]
Obrigado!
