### ISSUE TITLE
Call to a member function getGroups() on null

### ISSUE THREAD

**Issue by ondequadre** [codeigniter4/shield#210]
I point out that when the logout is performed, an error occurs in the development environment with the toolbar active, as shown in the attached image. In production environment or disabling the toolbar the error does not appear.

![error](https://user-images.githubusercontent.com/4273155/172062823-00be016a-28ce-44ac-aedc-6f74bb717f9a.png)

**Comment by datamweb** [comment]
Hello @ondequadre .
This error is due to the fact that in Table `auth_groups_users` without a group are user registered.
Please send the output of the following command for review if you are using version `CI4.2`.
`php spark db:table auth_groups_users`

**Comment by ondequadre** [comment]
Hello @datamweb, here the output:

`CodeIgniter v4.2.0 Command Line Tool - Server Time: 2022-06-05 21:17:46 UTC+02:00


Data of Table "auth_groups_users":

+----+---------+------------+--------------------+
| id | user_id | group      | created_at         |
+----+---------+------------+--------------------+
| 1  | 1       | superadmin | 2022-06-05 17:4... |
| 2  | 2       | user       | 2022-06-05 19:1... |
+----+---------+------------+--------------------+`

**Comment by kenjis** [comment]
I've checked, but can't reproduce the error.

If you logged out, the following `if` statement would be `false`.
How did you logout?

https://github.com/codeigniter4/shield/blob/f2160b0eb41b986c56ad225f9375f6d9e18e6433/src/Collectors/Auth.php#L65-L67

**Comment by datamweb** [comment]
There is a corner of this error.
I had the same problem two days ago.
I tried to repeat the mistake so I could write a test, but it failed.

**Comment by kenjis** [comment]
> There is a corner of this error.

What do you mean?

**Comment by datamweb** [comment]
@kenjis  after login ,If the first time `http://localhost:8080/logout` is called, an error is displayed.
Then, if `http://localhost:8080/logout`  called again, the user will **logout  successfully** and no error will be displayed.

**Step 1 : login**

![login](https://user-images.githubusercontent.com/9530214/172079365-327ed7b6-fac3-4697-b8ba-a7ad4d11a178.png)

**step 2 : http://localhost:8080/logout**

![logoutwhitError](https://user-images.githubusercontent.com/9530214/172079413-b7cb7a9a-b866-473d-a99c-b09ec354c8fd.png)


**step 3 : http://localhost:8080/logout**

![logouSu](https://user-images.githubusercontent.com/9530214/172079430-0a25cbbb-97fc-4d6c-b0f0-9cb4ae60f48c.png)



@ondequadre  **Do you confirm this?**

**Comment by kenjis** [comment]
@datamweb Please check #211 if it fixes the problem.

**Comment by ondequadre** [comment]
@datamweb Yes I confirm that is exactly what happens

**Comment by datamweb** [comment]
@ondequadre This case was resolved #211 . And waiting for merge.
 Thanks for your report.
