### ISSUE TITLE
Could not find a version of package codeigniter4/shield matching your minimum-stability (stable). Require it with an explicit version constraint allowing its desired stability.

### ISSUE THREAD

**Issue by jlopes90** [codeigniter4/shield#217]
I'm using codeigniter [appstarter](https://github.com/codeigniter4/appstarter) v4.2.0

![Captura de ecrã 2022-06-08 133529](https://user-images.githubusercontent.com/50026015/172617724-434e02da-e76c-4f5a-8797-3083e897d397.jpg)

**Comment by kenjis** [comment]
See [forum](https://forum.codeigniter.com/showthread.php?tid=82003&pid=396837#pid396837), https://github.com/codeigniter4/shield/issues/207, https://github.com/codeigniter4/shield/issues/157

**Comment by jlopes90** [comment]
Thank you

**Comment by kenjis** [comment]
Added the instruction in the docs:
https://github.com/codeigniter4/shield/blob/develop/docs/0%20-%20install.md#installation
