### ISSUE TITLE
fix: setup missing "use"

### ISSUE THREAD

**Issue by jlopes90** [codeigniter4/shield#219]
https://github.com/codeigniter4/shield/blob/45a38424233f4278991616160bed05dbb6193923/src/Commands/Setup.php#L111
`'use CodeIgniter\\Config\\BaseConfig;' => 'use CodeIgniter\\Shield\\Config\\Auth as ShieldAuth;',`

---

https://github.com/codeigniter4/shield/blob/45a38424233f4278991616160bed05dbb6193923/src/Commands/Setup.php#L123

`'use CodeIgniter\\Config\\BaseConfig;' => 'use CodeIgniter\\Shield\\Config\\AuthGroups as ShieldAuthGroups;',`

**Comment by datamweb** [comment]
Hello @jlopes90 ,
To better understand this, you need to know function `strtr`.
Here is the link [strtr](https://www.php.net/manual/en/function.strtr.php)  to its description.

**Comment by jlopes90** [comment]
eu já testei shield:setup

current: `'use CodeIgniter\\Config\\BaseConfig;' => 'CodeIgniter\\Shield\\Config\\Auth as ShieldAuth;',`

![image](https://user-images.githubusercontent.com/50026015/172682570-a3bc8be9-0c5e-493c-b9c5-b05be5198dd0.png)

modify: `'use CodeIgniter\\Config\\BaseConfig;' => 'use CodeIgniter\\Shield\\Config\\Auth as ShieldAuth;',`

![image](https://user-images.githubusercontent.com/50026015/172683869-afe10bf8-b001-4f28-bf2d-4a1eb2e2237e.png)

**Comment by kenjis** [comment]
@jlopes90 Thanks.
I sent a PR: #220
