### ISSUE TITLE
Register without username

### ISSUE THREAD

**Issue by jlopes90** [codeigniter4/shield#224]
I register without username, gives error.

Error message:
https://user-images.githubusercontent.com/50026015/172833798-59665122-053b-407c-803d-474d617ddc9b.png

**Comment by MGatner** [comment]
I think this means `getInsertId()` failed to return a matching user ID, yet `save()` still passed. I can't figure out a scenario where this would be true, except for maybe a race condition (which seems unlikely?). 

Can you post your code or any additional changes you made so we can try to recreate it?

**Comment by jlopes90** [comment]
The error was `"there is no data to insert"` is doing `!$users->save($user)` without username.

**Comment by datamweb** [comment]
@jlopes90 please [see ](https://github.com/codeigniter4/shield/discussions/192#discussioncomment-2859306).

**Comment by datamweb** [comment]
> > @jlopes90 please [see ](https://github.com/codeigniter4/shield/discussions/192#discussioncomment-2859306).
> 
> I did it now, still the same error.

It seems that Shield **needs changes** to implement this method.

**Comment by kenjis** [comment]
I sent a PR #232.

**Comment by MGatner** [comment]
As @kenjis pointed out in that PR, the root of the issue is that the overridden `save()` method sometimes returns `true` even when it fails.
