### ISSUE TITLE
logout but logged in is true

### ISSUE THREAD

**Issue by jlopes90** [codeigniter4/shield#225]
I ended up doing "logout" but "logged in" is still true.

**Comment by jlopes90** [comment]
One thing, "shield" is beta or release?

**Comment by jlopes90** [comment]
> See [here](https://github.com/codeigniter4/shield/releases/tag/v1.0.0-beta) for the answer. Also, if possible, **please send your questions** from [this section](https://github.com/codeigniter4/shield/discussions/categories/q-a).

Never seen, thank you.

**Comment by jlopes90** [comment]
https://github.com/codeigniter4/shield/blob/45f7522e597fee438767f6dfdfab0d440181dcb6/src/Authentication/Authenticators/Session.php#L704-L712

current: the `$this->user` receives is always null.

to

```
public function logout(): void
{
    $userId = $this->getSessionKey('id');
    $this->user = $this->provider->findById($userId);

    if ($this->user === null) {
        return;
    }

    ...
}
```


modify: I think it would be useful to check if there is a session with id.

**Comment by kenjis** [comment]
I confirmed the bug, and sent a PR: #231
