### ISSUE TITLE
Blank login form (email and password) without username

### ISSUE THREAD

**Issue by jlopes90** [codeigniter4/shield#237]
I tested the blank login form (email and password), it gave an error because of `username`.

![image](https://user-images.githubusercontent.com/50026015/173240436-534b49f2-046c-4711-9339-3e7236d37a16.png)

https://github.com/codeigniter4/shield/blob/cbd9bfdcdfef2d7d21d9c2571d6b28ec69bcf353/src/Authentication/Authenticators/Session.php#L256-L263

to 

```
$this->loginModel->recordLoginAttempt( 
     $idType, 
     $credentials['email'] ?? $credentials['username'] ?? '',
     $success, 
     $ipAddress, 
     $userAgent, 
     $userId 
 );
```

**Comment by datamweb** [comment]
Did I get it right, you deleted both the **email** and the **username** in the login form?

**Comment by jlopes90** [comment]
> Did I get it right, you deleted both the **email** and the **username** in the login form?

that's not it, the login form has an email and password, I tested it without filling it in and got this error.

**Comment by datamweb** [comment]
In general, you should not send data to the database **without validation**. **This causes security problems**.
In file `RegisterController.php` you must have the following values.

 ```php
    /**
     * Returns the rules that should be used for validation.
     *
     * @return string[]
     */
    protected function getValidationRules(): array
    {
        return [
            //'username'         => 'required|alpha_numeric_space|min_length[3]|is_unique[users.username]',
            'email'            => 'required|valid_email|is_unique[auth_identities.secret]',
            'password'         => 'required|strong_password',
            'password_confirm' => 'required|matches[password]',
        ];
    }
```

**Comment by datamweb** [comment]
Can you send a **PR**?

**Comment by jlopes90** [comment]
> Você pode enviar um **PR** ?

I can do it, but they do it differently.

**Comment by datamweb** [comment]
@jlopes90  team members are very friendly and with you.
Sending **PR** on your behalf is not a problem,
In the worst case, your **PR** will be closed, either by yourself or until the problem is solved.
**Do not be afraid to participate.** 👍 
**CI** Members are all with you.

**Comment by kenjis** [comment]
Yes, missing validation in the login form is a bug, or very bad practice.

**Comment by lonnieezell** [comment]
I agree - there should have been validation there.

**Comment by datamweb** [comment]
I believe it is better to apply **validations to models** as well.
**Why?** Suppose a developer customizes the login system using the Shield functions. For example, through API ...  In this case, if it does something wrong, the data will be transferred to the **database without validation**, and this is very bad.

**Comment by jlopes90** [comment]
PR: https://github.com/codeigniter4/shield/pull/242
