### ISSUE TITLE
SQLite3 error

### ISSUE THREAD

**Issue by Traveliter** [codeigniter4/shield#240]
Could we update the install docs to avoid the following issue?

When doing the spark migrate --all command I get the following error:

Unable to connect to the database.
Main connection [SQLite3]: Class "SQLite3" not found

I fixed it by getting rid of the test folder, but it took me half an hour to work out what the problem was. Perhaps a note in the installation section would save others some time.

**Comment by datamweb** [comment]
Hi @Traveliter ,
Did you set the following value in file `.env`?
` CI_ENVIRONMENT = testing`

**Comment by Traveliter** [comment]
Hi datamweb,
I had development set:

CodeIgniter v4.2.0 Command Line Tool - Server Time: 2022-06-13 17:45:25 UTC+10:00

Your environment is currently set as development.

**Comment by datamweb** [comment]
What about file `config/Database.php`?
Is the following value set?

```php 
public $defaultGroup = 'tests';
```

**Comment by kenjis** [comment]
This error is because there is a sample migration file `tests/_support/Database/Migrations/2020-02-22-222222_example_migration.php` when you install CI4.

`spark migrate --all` finds all migration files in all namespaces, and Instantiates found classes.
And at that time, the migration class tries to connect to the database.
But you don't have SQLite extension enabled, so `Class "SQLite3" not found` error occurs.

**Comment by kenjis** [comment]
This error seems to be common.
https://github.com/lonnieezell/myth-auth/issues/189#issuecomment-615934532

**Comment by kenjis** [comment]
I sent a PR  #241

**Comment by Traveliter** [comment]
> What about file `config/Database.php`? Is the following value set?
> 
> ```
> public $defaultGroup = 'tests';
> ```

datamweb,
I have public $defaultGroup = 'default'; in Database.php
default is set in .env to my mariadb settings which all works fine.
I don't have the SQLite extension in my php setup

**Comment by kenjis** [comment]
@Traveliter If you don't use SQLite3, I recommend you update the `tests` database config:
https://github.com/codeigniter4/CodeIgniter4/blob/5f0233f5736f546273a3f1a76e75bc5779b6af0c/app/Config/Database.php#L59-L78

When you write test code, you will use it.

**Comment by datamweb** [comment]
> datamweb, I have public $defaultGroup = 'default'; in Database.php default is set in .env to my mariadb settings which all works fine. I don't have the SQLite extension in my php setup


**PR** by **Kenjis** was submit to prevent such a recurrence.

**Thanks for your reply and report.**

**Comment by MGatner** [comment]
If this is happening across multiple packages then we should probably pull those files from the AppStarter.

**Comment by kenjis** [comment]
I have sent a PR to prevent the error from occurring to CodeIgniter main repository.
https://github.com/codeigniter4/CodeIgniter4/pull/6117
