### ISSUE TITLE
UserModel::save() can't save new User email/password

### ISSUE THREAD

**Issue by kenjis** [codeigniter4/shield#253]
After calling `parate::save()`, `UserModel::save()` tries to save Email identity.
But when inserting User, `$this->find($this->db->insertID())` returns the User without email/passsword.

https://github.com/codeigniter4/shield/blob/4c8b53c9b6fd7701cba804e86df78bdeef48dc42/src/Models/UserModel.php#L205-L216

**Comment by MGatner** [comment]
You're right, it is a logic loop. I want this whole method to go away anyways. I have an idea for a fix in the framework - it would mean waiting on 4.3 though so we might need a workaround until then.
