### ISSUE TITLE
UserModel::save() can't update User's email/password

### ISSUE THREAD

**Issue by kenjis** [codeigniter4/shield#254]
When updating User's email/password, `parent::save($data)` may returns DataException (no data to update),
in that case, email/password is not updated.

https://github.com/codeigniter4/shield/blob/4c8b53c9b6fd7701cba804e86df78bdeef48dc42/src/Models/UserModel.php#L202-L231

**Comment by jadsy2107** [comment]
Please not the workaround, specifying
`$user->active = <1 or 0>`

Before 
`save($user) `

is called

**Comment by MGatner** [comment]
https://github.com/codeigniter4/shield/issues/253#issuecomment-1164303404

**Comment by caosdp-rs** [comment]
I have the same problem
I added this
   'last_active'=> new Time('now'),
