### ISSUE TITLE
Validation rules for username

### ISSUE THREAD

**Issue by kenjis** [codeigniter4/shield#260]
The current validation rules for username permit spaces.

https://github.com/codeigniter4/shield/blob/0e1f3780435500d1ca6c030bcff17cd634cd0521/src/Database/Migrations/2020-12-28-223112_create_auth_tables.php#L14

https://github.com/codeigniter4/shield/blob/0e1f3780435500d1ca6c030bcff17cd634cd0521/src/Controllers/RegisterController.php#L134

https://github.com/codeigniter4/shield/blob/0e1f3780435500d1ca6c030bcff17cd634cd0521/src/Models/UserModel.php#L121

> I'm speaking anecdotally, I don't have an RFC reference or anything, but I would never anticipate allowing a space in a username and I also know many services that allow periods, especially so you can use Gmail-style credentials: `matthew.gatner@gmail.com => matthew.gatner`
https://github.com/codeigniter4/shield/pull/242#discussion_r906804934

**Comment by kenjis** [comment]
If we permit dots and don't allow spaces, the rule should be like these?

```
'required|max_length[30]|regex_match[/\A[a-zA-Z0-9\.]+\z/]|min_length[3]|is_unique[users.username]'
```

**Comment by MGatner** [comment]
Thanks for opening this @kenjis. I will do a little research, as I expect there are some standards around this that would better serve us than my anecdotal preferences. 😊 Maybe @lonnieezell can chime in if spaces were intentionally supported for some reason.

**Comment by MGatner** [comment]
Really great read here, not apparently on character validation but in taking some notes: https://www.b-list.org/weblog/2018/feb/11/usernames/

1. Username uniqueness should be case insensitive

**Comment by kenjis** [comment]
I sent a PR #268 that has  config `$validationRulesUsername`.

**Comment by kenjis** [comment]
We changed the validation rules. See #268
