### ISSUE TITLE
Links created with route_to() do not work when baseURL has subfolders

### ISSUE THREAD

**Issue by parisiam** [codeigniter4/shield#267]
Let's say `baseURL` is `https://mydomain.com/subfolder`.
Then `route_to('login')` is `/login`.

But it should be `/subfolder/login`.

I suggest to change all `route_to(...)` to `site_url(route_to(...))`.

**Comment by kenjis** [comment]
Good suggestion!
Does anybody try to send a PR?

**Comment by MGatner** [comment]
Is this an issue with the framework in general? I was under the impression that `route_to()` was safe to use as a fully-routed URI. Guess I will go do some research...

**Comment by MGatner** [comment]
... back! So I was wrong, `route_to()` is aptly named in that it returns the *route*, not the actual URI segments. However the User Guide is misleading about this and has examples of using it as a URI path, which is incorrect:
```php
<!-- Generate the relative URL to link to user ID 15, gallery 12: -->
<a href="<?= route_to('Galleries::showUserGallery', 15, 12) ?>">View Gallery</a>
<!-- Result: '/users/15/gallery/12' -->
```
https://codeigniter4.github.io/CodeIgniter4/incoming/routing.html#reverse-routing

What we do have is the less-documented method `url_to()`, which is essentially `site_url(route_to())` with a little extra lookup logic: 
https://codeigniter4.github.io/CodeIgniter4/helpers/url_helper.html?highlight=url_to#url_to

That is the correct function to use here.
