### ISSUE TITLE
preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated

### ISSUE THREAD

**Issue by wangling97** [codeigniter4/shield#289]
Does this application not support using PHP 8.1? I just installed Shield and tried to use Email2Fa, and I got this error message. The description says that the error is in SYSTEMPATH\Email\Email.php at line 466.

![ufY3l6](https://user-images.githubusercontent.com/9530214/209454604-6a67ae0a-9485-452b-add4-0571604a62fe.png)

This a screen shoot : https://im.ge/i/ufY3l6

**Comment by datamweb** [comment]
hello @wangling97 ,
Shield also supports version **PHP 8.1**.
Your problem is related to **not setting** the values in the **email configuration file**.
Please set the values through file `app\Config\Email.php`.
```php
<?php

namespace Config;

use CodeIgniter\Config\BaseConfig;

class Email extends BaseConfig
{
  
    /**
     * @var string
     */
    public $fromEmail = 'your_mail@yahoo.com';

    /**
     * @var string
     */
    public $fromName = 'your name';
}
```
and other cases

**Comment by wangling97** [comment]
Can this be used with public email like gmail? and are there any special settings if using a private email server?

**Comment by datamweb** [comment]
> Can this be used with public email like gmail? 

**Yes**, see https://github.com/codeigniter4/CodeIgniter4/issues/6217#issuecomment-1172887117

> and are there any special settings if using a private email server?

Yes. see [Email Preferences](https://codeigniter.com/user_guide/libraries/email.html#id6)

**Comment by MGatner** [comment]
I'm closing this since the originating error message wasn't even in this library. @wangling97 If you need more help please visit the CodeIgniter forums or Slack channel.

**Comment by kenjis** [comment]
This seems to be a documentation problem.

**Comment by datamweb** [comment]
Yes, I agree to update this item.

Additionally, I noticed that using `settings` to configure email does not work properly. Maybe we need to modify the email helper. In this regard, I am not sure whether it is a bug or my understanding of the `settings` is wrong.

**Comment by kenjis** [comment]
I checked the code of Shield, but it seems okay because it uses `settings()` when sending emails.
Is it really a Shield issue?

**Comment by datamweb** [comment]
Can you share the output of the following command (with sensitive information removed)?
```console
php spark db:table settings
```

**Comment by kenjis** [comment]
I just read the code, not actually try to save them in the database.

**Comment by datamweb** [comment]
Well, 
For example, I set the value to `$SMTPUser` below (`app/Config/Email.php`).
```php
public $SMTPUser = 'p.parsa.dadashi...';
```
**Everything works fine.**

Now I change its value `$SMTPUser` below (`app/Config/Email.php`).
```php
public $SMTPUser = '';
```
And I have the following values in the settings.
```console
P:\Bug\4.3>php spark db:table settings

CodeIgniter v4.2.11 Command Line Tool - Server Time: 2022-12-25 09:19:43 UTC+00:00

Data of Table "settings":

+----+-------+----------+--------------------+--------+---------+--------------------+--------------------+
| id | class | key      | value              | type   | context | created_at         | updated_at         |
+----+-------+----------+--------------------+--------+---------+--------------------+--------------------+
| 1  | Email | SMTPUser | p.parsa.dadashi... | string |         | 2022-12-25 01:2... | 2022-12-25 01:2... |
+----+-------+----------+--------------------+--------+---------+--------------------+--------------------+


```
My guess is that it still works fine, but no email is sent.

What is in the configuration documents, the priority is as follows.

**"Setting with a context > Setting without context > Config value > null"**

Do I have a problem understanding the `Setting` ?

**Comment by kenjis** [comment]
> Do I have a problem understanding the Setting ?

No.
I think it should work.

`email()` function uses `setting('Email.SMTPUser')`:
https://github.com/codeigniter4/shield/blob/ca7335c717efcd4fadfc219cdb2c0a3bae758ae2/src/Helpers/email_helper.php#L22

**Comment by datamweb** [comment]
> I think it should work.

Oh @kenjis, I forgot to mention this. Everything works fine.
My problem was that I had customized `email_helper.php`.
