### ISSUE TITLE
shield:setup sets up its routes in an unfortunate location

### ISSUE THREAD

**Issue by mv-steven** [codeigniter4/shield#295]
Not a big issue but something that stood out during the installation process.

I have an existing route group defined in Routes.php, and shield:setup put the route definition in the group closure, like this:
```php
$routes->group('api', function($routes) {

service('auth')->routes($routes); <===
    $routes->map([
        ...
    ]);
});
```
Again, not a big issue, anyone using code modification tools should be reviewing what changes are being made. Just wanted to make sure this was known.

**Comment by kenjis** [comment]
It is difficult to find the following code block with regex.

```php
$routes->group('api', function($routes) {
    ...
});
```

So a fundamental solution seems difficult in the current situation.
https://github.com/codeigniter4/CodeIgniter4/pull/6133#issue-1273276433 also finds a line and adds a new line before/after it.

**Comment by mv-steven** [comment]
I bet you could use token_get_all to determine whether a given line is in between a closure's (or something else's) braces

**Comment by kenjis** [comment]
Yes, we want a method to
1. find the last `$routes->...;` block
2. add new line `service('auth')->routes($routes);` after it

**Comment by kenjis** [comment]
This bug was fixed in `develop`.
Please check.
