### ISSUE TITLE
Missing back link on Magic Link form

### ISSUE THREAD

**Issue by parisiam** [codeigniter4/shield#299]
I suggest to add a link back to the login page on the Magic Link form.
What do you think ?
![CleanShot20220716142055](https://user-images.githubusercontent.com/627813/179354756-06ef619a-9f9f-4320-8447-8849f3d70089.jpg)

**Comment by datamweb** [comment]
I agree. This seems useful.

**Comment by kenjis** [comment]
No problem.

**Comment by datamweb** [comment]
Hello @parisiam ,
can you send PR in this regard?

**Comment by datamweb** [comment]
Well, I don't think I'm getting a response from **parisiam** .
@jlopes90, I'm interested in you sending PR on this matter.
can you ?

**Comment by jlopes90** [comment]
> Well, I don't think I'm getting a response from **parisiam** . @jlopes90, I'm interested in you sending PR on this matter. can you ?

yes

**Comment by jlopes90** [comment]
https://github.com/codeigniter4/shield/pull/375
