### ISSUE TITLE
Getting the appropriate last login of a user

### ISSUE THREAD

**Issue by sammyskills** [codeigniter4/shield#300]
I think the `lastLogin()` does not return the appropriate last login record of a user. Here's the code:
https://github.com/codeigniter4/shield/blob/93f607f87e8690d897d8971829784364f42899b5/src/Models/LoginModel.php#L73
```
public function lastLogin(User $user): ?Login
{
    return $this->where('success', 1)
        ->where('user_id', $user->id)
        ->orderBy('id', 'desc')
        ->first();
}
```
The code above returns the first record which will always get the current successful login attempt instead of the last successful login attempt which I think is the purpose of lastLogin (IMO).

I think the method is supposed to return the second row, and I can create a PR if I'm correct.

**Comment by kenjis** [comment]
It depends on the use case.

If it is used to display the previous login time when a site user logs in, you are correct.
But I'm not sure the method is for it.

**Comment by lonnieezell** [comment]
This is correct for the intended use case - which was more for an admin area and being able to see the history of users. I think of a `previousLogin()` method would make a nice addition, though, if you wanted to create a PR?

**Comment by sammyskills** [comment]
Yeah , I saw looking at a general use case based on what I've seen in some applications. 

I'll create a PR for `previousLogin()` as suggested.

Thank you.

**Comment by sammyskills** [comment]
I've created a **PR** #301 to address this issue.

Thanks everyone.
