### ISSUE TITLE
Migration error: specified key was too long

### ISSUE THREAD

**Issue by sammyskills** [codeigniter4/shield#303]
Hi all,

I just ran a migration command but it returned error in the terminal and I think it has to do with the `auth_identities` table. See screenshot below:

![image](https://user-images.githubusercontent.com/8720569/179482877-1727bd1d-50bd-457f-9fb6-d023ea409dd6.png)

**Comment by kenjis** [comment]
Use InnoDB, not MyISAM.

**Comment by sammyskills** [comment]
Ok, will do.
Thanks.
