### ISSUE TITLE
Please Provide Option to add  groups dynamically 

### ISSUE THREAD

**Issue by srikant-kumar** [codeigniter4/shield#304]
Many Application Needs Dyanmic Role Creation Using Form and assign the permission using checkbox. There is static set of array written in AuthGroups.php so if we want give option to user to create a new group for their application then how we can do ?

**Comment by lonnieezell** [comment]
Shield uses our [Settings](https://github.com/codeigniter4/settings) library underneath. This means that you can create an area for your users to change roles/permissions and then use the `setting()` method to save them to the database. This is then automatically recognized by Shield. 

See this related code in my project, [Bonfire](https://github.com/lonnieezell/Bonfire2/blob/develop/src/Groups/Controllers/GroupSettingsController.php#L70) for an example of how you might do that.
