### ISSUE TITLE
UserModel::findById() shows Error

### ISSUE THREAD

**Issue by salain** [codeigniter4/shield#307]
When trying to find user by id  with identities return error "Attempt to read property \"id\" on int" in "vendor/codeigniter4/shield/src/Models/UserModel.php" on line 92

`$profile = (new \CodeIgniter\Shield\Models\UserModel())->withIdentities()->findById($Id);`

But if I use :
`$profile = (new \CodeIgniter\Shield\Models\UserModel())->where('id',$Id)->withIdentities()->findAll($Id);` 

It return the user record with the identity record duplicated. 

Am I missing something?
Regards

**Comment by kenjis** [comment]
Thank you for reporting.
I sent a PR #308

**Comment by salain** [comment]
Thanks @kenjis 
I have applied your PR and it looks all good now
Regards
