### ISSUE TITLE
RememberMe: Unknown column 'users.remember' in 'where clause'

### ISSUE THREAD

**Issue by sammyskills** [codeigniter4/shield#314]
Hi all,

I just tried to login with the remember-me checkbox 'checked', but it returned an error message:

```
mysqli_sql_exception #1054
Unknown column 'users.remember' in 'where clause'
```

**Comment by kenjis** [comment]
Do you use the latest `develop` branch?
Can you show back trace?

There is no such column `users.remember`.
https://github.com/codeigniter4/shield/blob/121ac4a9c44bd67fcd1f9130e7119ab9b5477634/src/Database/Migrations/2020-12-28-223112_create_auth_tables.php#L13-L21

**Comment by sammyskills** [comment]
Yes, I'm using the latest `develop` branch, and I checked the db also, that column doesn't exist. 
Here's the back trace:
![image](https://user-images.githubusercontent.com/8720569/180736290-bba84458-4184-45b6-8576-7cc799c3b78b.png)

**Comment by kenjis** [comment]
What's your `$validFields` value in Config\Auth ?
https://github.com/codeigniter4/shield/blob/121ac4a9c44bd67fcd1f9130e7119ab9b5477634/src/Config/Auth.php#L222-L225

**Comment by sammyskills** [comment]
![image](https://user-images.githubusercontent.com/8720569/180754248-68eccd19-b59d-4e79-8af4-bcc05eb118c0.png)

**Comment by kenjis** [comment]
It seems you customized `LoginController::loginAction()`.
It seems the cause of the error.

**Comment by kenjis** [comment]
Please `unset($credentials['remember'])`  before the following line.

```php
$result = auth('session')->remember($remember)->attempt($credentials);
```

**Comment by sammyskills** [comment]
Yes, I customized the `loginAction()` method, but I don't expect it to cause any error. 
I tried to make the login form accept either username or email address. Here's my code:
```
public function loginAction(): RedirectResponse
{
    // The post request
    $post_request = $this->request->getPost();
        
    // Determine the credential type
    $login = $post_request['login'];
    $type = filter_var($login, FILTER_VALIDATE_EMAIL) ? 'email' : 'username';
    $type == 'email' ? $post_request['email'] = $login : $post_request['username'] = $login;
    // Unset the login array
    unset($post_request['login']);

    // Run validation as it isn't covered in the model
    if ( ! $this->validateData($post_request, 'login_'.$type) ) return redirect()->back()->withInput()->with('errors', $this->validator->getErrors());
        
    $credentials             = $post_request;
    $credentials             = array_filter($credentials);
    $credentials['password'] = $this->request->getPost('password');
    $remember                = (bool) $this->request->getPost('remember');

    // Attempt to login
    $result = auth('session')->remember($remember)->attempt($credentials);
    if (! $result->isOK()) {
        return redirect()->route('login')->withInput()->with('error', $result->reason());
    }

    // If an action has been defined for login, start it up.
    $actionClass = setting('Auth.actions')['login'] ?? null;
    if (! empty($actionClass)) {
        return redirect()->to(route_to('auth-action-show'))->withCookies();
    }

    return redirect()->to(config('Auth')->loginRedirect())->withCookies();
}
```

**Comment by sammyskills** [comment]
> Please `unset($credentials['remember'])` before the following line.
> 
> ```
> $result = auth('session')->remember($remember)->attempt($credentials);
> ```

This worked, thank you.

On a second thought, how about allowing users to login using either username or email address? That would make a nice addition IMO as users are not restricted to using only their email address. 

In addition to my code, we can still get the `validFields` using:
```
$credentials  = array_filter($post_request, function($k) { return in_array($k, setting('Auth.validFields')); }, ARRAY_FILTER_USE_KEY);
```
What do you think @kenjis @MGatner @lonnieezell ?

**Comment by kenjis** [comment]
I don't see the advantage of being able to log in with username. 
If the username is used to display on the site, anyone can know it and easily know the user's login ID, making it easier to attack the account.

**Comment by kenjis** [comment]
In your customization, the following code is not good.

```php
$post_request = $this->request->getPost();
// ...
$credentials             = $post_request;
```

It gets all POSTed fields and sets them to `$credentials`.
You should set only credentials to `$credentials`.

**Comment by sammyskills** [comment]
> I don't see the advantage of being able to log in with username. If the username is used to display on the site, anyone can know it and easily know the user's login ID, making it easier to attack the account.

Well, this depends on the context. There are applications that also display the email of a user and just as you've pointed out, anyone can know that also and easily know the user's login ID.

I was just looking at giving users that flexibility of not having to remember their username/email as any of them can be used as the login ID. `Myth/Auth` has this feature likewise other applications, but if it is not necessary here, then it's fine.



> In your customization, the following code is not good.
> 
> ```
> $post_request = $this->request->getPost();
> // ...
> $credentials             = $post_request;
> ```
> 
> It gets all POSTed fields and sets them to `$credentials`. You should set only credentials to `$credentials`.

I already updated my code to this:
```
$credentials  = array_filter($post_request, function($k) { return in_array($k, setting('Auth.validFields')); }, ARRAY_FILTER_USE_KEY);
```

Thank you.

**Comment by MGatner** [comment]
> I already updated my code to this

I think you just re-coded [array_intersect_key](https://www.php.net/array_intersect_key).

**Comment by sammyskills** [comment]
Yeah, you're right. 

Thank you.

**Comment by kenjis** [comment]
> Well, this depends on the context. There are applications that also display the email of a user and just as you've pointed out, anyone can know that also and easily know the user's login ID.

Yes, you are correct. But I don't see such a site recently.

I just don't see the need for username to be login ID, since login ID is something I store in my browser, etc. so I don't have to remember either. Or if the login form has only email field, I also don't need to remember.

If there is a really great need for both to be login IDs, then I think it should be configurable that way. In that case, I think the default should still be just email.

**Comment by sammyskills** [comment]
Noted.
