### ISSUE TITLE
[PostgreSQL] Issue error register new user 

### ISSUE THREAD

**Issue by caosdp-rs** [codeigniter4/shield#328]
ErrorException
pg_query(): Query failed: ERROR: column "active" is of type smallint but expression is of type boolean
LINE 1: UPDATE "users" SET "active" = TRUE, "updated_at" = '2022-07-...

{PHP internal code} — CodeIgniter\Debug\Exceptions->errorHandler ( arguments )

SYSTEMPATH\Database\Postgre\Connection.php : 135 — pg_query()

SYSTEMPATH\Database\BaseConnection.php : 695 — CodeIgniter\Database\Postgre\Connection->execute ( arguments )

$sql
UPDATE "users" SET "active" = TRUE, "updated_at" = '2022-07-29 18:15:52'
WHERE "users"."id" IN ('1')

**Comment by caosdp-rs** [comment]
ErrorException
pg_query(): Query failed: ERROR: column "active" is of type smallint but expression is of type boolean
LINE 1: UPDATE "users" SET "active" = TRUE, "updated_at" = '2022-07-...

{PHP internal code} — CodeIgniter\Debug\Exceptions->errorHandler ( arguments )

SYSTEMPATH\Database\Postgre\Connection.php : 135 — pg_query()

SYSTEMPATH\Database\BaseConnection.php : 695 — CodeIgniter\Database\Postgre\Connection->execute ( arguments )

$sql
UPDATE "users" SET "active" = TRUE, "updated_at" = '2022-07-29 18:15:52'
WHERE "users"."id" IN ('1')

**Comment by MGatner** [comment]
We have some other discussions going about database boolean types; I can't find them right now on mobile but I'm fairly certain this is the same.

**Comment by kenjis** [comment]
This is because the column type is `tinyint`:
https://github.com/codeigniter4/shield/blob/835bec6a6bfde617f5f5c3f14935e8b61282c20b/src/Database/Migrations/2020-12-28-223112_create_auth_tables.php#L17
But the code set `true`:
https://github.com/codeigniter4/shield/blob/835bec6a6bfde617f5f5c3f14935e8b61282c20b/src/Models/UserModel.php#L210

**Comment by kenjis** [comment]
Therefore `$user->active` is `bool` when reading, but we must set `int` when writing,
because of the current Entity behavior.

**Comment by MGatner** [comment]
I still can't find the thread I've been looking for but here are some partially-related:
* https://github.com/codeigniter4/CodeIgniter4/pull/4907
* https://github.com/codeigniter4/CodeIgniter4/pull/2563

I think this is a framework issue. Many databases use `0`/`1` for `false`/`true` (even aliasing `BOOL` to `TINYINT`) so CodeIgniter gets away with vague type conversations on the inbound data. PostgreSQL seems to support real, distinct native booleans and strict mode won't translate between 0s and 1s.

**Comment by MGatner** [comment]
The fix for Shield might be to change the migration to use `boolean` instead of `tinyint`. It should affect MySQL/SQLite because that will alias to `tinyint` anyways but it will allow the boolean inputs for PostgreSQL.

**Comment by kenjis** [comment]
> to change the migration to use boolean instead of tinyint

It seems good idea. I guess at least this PostgreSQL error will be solved.

However, I believe that Entity needs to be modified for a fundamental solution to properly handle types.

**Comment by MGatner** [comment]
While Entity could work, my guess would be that this should be handled in the database layer, since it is a fundamental difference between database drivers. If we try to push it into Entity then our entity instances will need to have some understanding of the underlying store, which is a violation of the repository pattern.

**Comment by kenjis** [comment]
> this should be handled in the database layer

It seems difficult. Because the database layer does not have column types
unless getting table metadata.

**Comment by MGatner** [comment]
It shouldn't need the column types, it just needs to know how it's database engine handles booleans. I _think_ MySQL/SQLite3 will accept `true` and `false` even with strict mode; PostgreSQL would need to do whatever input conversion it requires, like:
```php
foreach ($data as $i => $value) {
    if ($value === true) {
        $data[$i] = new RawSQL('true');
    }
...
```

That's obviously not the right code but hopefully you get my gist.

**Comment by MGatner** [comment]
Actually I think I just understood what you meant. We don't need column types for _writing_ data but we would need it for _reading_ data since MySQL (e.g.) will return `0`/`1` due to its storage as `TINYINT`. In other words this code won't work the same across different database drivers:
```php
$user->active = true;
$id = model(UserModel::class)->insert($user);
$user = model(UserModel::class)->find($id);
$user->active = true;
var_dump($user->hasChanged());
```

**Comment by MGatner** [comment]
I don't think there is a way to solve this. The database drivers have inherently different feature sets and we either standardize (and lose PostgreSQL features) or leave them "as is", in which case the developer will have to deal with the underlying behavior differences.

**Comment by kenjis** [comment]
This is because only Postgre escape `bool` as `'TRUE'` or `'FALSE'`.

https://github.com/codeigniter4/CodeIgniter4/blob/170d84a8f3fdd82eecac94d6560eadda9b3df9cc/system/Database/BaseConnection.php#L1243-L1245
```php
        if (is_bool($str)) {
            return ($str === false) ? 0 : 1;
        }
```

https://github.com/codeigniter4/CodeIgniter4/blob/170d84a8f3fdd82eecac94d6560eadda9b3df9cc/system/Database/Postgre/Connection.php#L186-L188
```php
        if (is_bool($str)) {
            return $str ? 'TRUE' : 'FALSE';
        }
```

**Comment by MGatner** [comment]
Right. The problem isn't even PostgreSQL - it is that all other drivers interpolate booleans as `0` or `1` which is a one-way hash because `'0'` and `'1'` are also valid INT/DOUBLE/STRING values coming out of the database. I don't think there is a solution without introducing ORM-style schema awareness into Entity/Result.

**Comment by MGatner** [comment]
That would work fine. We could still cast as `bool` but it does make it confusing sometimes when the types don't align.

**Comment by kenjis** [comment]
I was able to make tests pass, but my conclusion is:
- use table column type in PHP

In this case, int, not bool. Because:
- if we use cast `boolean`, we must have setter to cast to int
- we can't use PHP type for `seeInDatabase()`

The following is the dirty hack:
```diff
diff --git a/src/Database/Migrations/2020-12-28-223112_create_auth_tables.php b/src/Database/Migrations/2020-12-28-223112_create_auth_tables.php
index 3c4ec9e..c3c39ac 100644
--- a/src/Database/Migrations/2020-12-28-223112_create_auth_tables.php
+++ b/src/Database/Migrations/2020-12-28-223112_create_auth_tables.php
@@ -136,13 +136,13 @@ public function down(): void
     {
         $this->db->disableForeignKeyChecks();
 
-        $this->forge->dropTable('users', true);
         $this->forge->dropTable('auth_logins', true);
         $this->forge->dropTable('auth_token_logins', true);
         $this->forge->dropTable('auth_remember_tokens', true);
         $this->forge->dropTable('auth_identities', true);
         $this->forge->dropTable('auth_groups_users', true);
         $this->forge->dropTable('auth_permissions_users', true);
+        $this->forge->dropTable('users', true);
 
         $this->db->enableForeignKeyChecks();
     }
diff --git a/src/Entities/Login.php b/src/Entities/Login.php
index 8d0f378..ed95389 100644
--- a/src/Entities/Login.php
+++ b/src/Entities/Login.php
@@ -13,4 +13,11 @@ class Login extends Entity
         'date'    => 'datetime',
         'success' => 'boolean',
     ];
+
+    public function setSuccess(bool $value)
+    {
+        $this->attributes['success'] = (int) $value;
+
+        return $this;
+    }
 }
diff --git a/src/Entities/User.php b/src/Entities/User.php
index 766fc66..d42b58e 100644
--- a/src/Entities/User.php
+++ b/src/Entities/User.php
@@ -229,6 +229,13 @@ public function setPasswordHash(string $hash): User
         return $this;
     }
 
+    public function setActive(bool $value): User
+    {
+        $this->attributes['active'] = (int) $value;
+
+        return $this;
+    }
+
     /**
      * Accessor method to grab the user's password hash.
      * Will cache it in $this->attributes, since it has
diff --git a/src/Entities/UserIdentity.php b/src/Entities/UserIdentity.php
index 9637779..e7ef68d 100644
--- a/src/Entities/UserIdentity.php
+++ b/src/Entities/UserIdentity.php
@@ -51,4 +51,11 @@ public function hashSecret(string $value): UserIdentity
 
         return $this;
     }
+
+    public function setForceReset(bool $value)
+    {
+        $this->attributes['force_reset'] = (int) $value;
+
+        return $this;
+    }
 }
diff --git a/src/Models/CheckQueryReturnTrait.php b/src/Models/CheckQueryReturnTrait.php
index 05b4921..a49f5a9 100644
--- a/src/Models/CheckQueryReturnTrait.php
+++ b/src/Models/CheckQueryReturnTrait.php
@@ -21,7 +21,7 @@ private function checkQueryReturn(bool $return): void
             $message = 'Query error: ' . $error['code'] . ', '
                 . $error['message'] . ', query: ' . $this->db->getLastQuery();
 
-            throw new DatabaseException($message, $error['code']);
+            throw new DatabaseException($message, (int) $error['code']);
         }
     }
 
diff --git a/tests/Controllers/LoginTest.php b/tests/Controllers/LoginTest.php
index d1a49da..8836816 100644
--- a/tests/Controllers/LoginTest.php
+++ b/tests/Controllers/LoginTest.php
@@ -85,7 +85,7 @@ public function testLoginActionEmailSuccess(): void
         $this->seeInDatabase('auth_logins', [
             'identifier' => 'foo@example.com',
             'user_id'    => $this->user->id,
-            'success'    => true,
+            'success'    => 1,
         ]);
         // Last Used date should have been set
         $identity = $this->user->getEmailIdentity();
@@ -147,7 +147,7 @@ public function testLoginActionUsernameSuccess(): void
         $this->seeInDatabase('auth_logins', [
             'identifier' => $this->user->username,
             'user_id'    => $this->user->id,
-            'success'    => true,
+            'success'    => 1,
         ]);
         // Last Used date should have been set
         $identity = $this->user->getEmailIdentity();
diff --git a/tests/Unit/UserModelTest.php b/tests/Unit/UserModelTest.php
index e411b6b..81cea24 100644
--- a/tests/Unit/UserModelTest.php
+++ b/tests/Unit/UserModelTest.php
@@ -67,7 +67,10 @@ public function testInsertUserArray(): void
         $user = $this->createNewUser();
 
         $userArray = $user->toArray();
-        $id        = $users->insert($userArray);
+        // Fix value type
+        $userArray['active'] = (int) $userArray['active'];
+
+        $id = $users->insert($userArray);
 
         $this->dontSeeInDatabase('auth_identities', [
             'user_id' => $id,
@@ -151,6 +154,9 @@ public function testUpdateUserArrayWithUserDataToUpdate(): void
         $user->active   = 1;
 
         $userArray = $user->toArray();
+        // Fix value type
+        $userArray['active'] = (int) $userArray['active'];
+
         $users->update(null, $userArray);
 
         $this->dontSeeInDatabase('auth_identities', [
```

**Comment by MGatner** [comment]
How about a new framework class `CodeIgniter\Entity\Cast\IntBoolCast`? This would store `0` and `1` attributes but return `false` and `true`, like you have here.

**Comment by kenjis** [comment]
`IntBoolCast` can remove the setters, but can't help `seeInDatabase()`.
Would you abandon `seeInDatabase()` in favor of using `bool` in PHP code?

**Comment by MGatner** [comment]
I don't use `seeInDatabase` much myself, preferring to stick to the model returns. I think any solution will have to acknowledge that booleans are a point of contention where cross-database support breaks. Id like to look into how other frameworks chose to handle this, though most of the big ones use ORMs which dodge the issue.

**Comment by kenjis** [comment]
I think `seeInDatabase` can't be helped anyway.

I sent #339
