### ISSUE TITLE
[PostgreSQL] Error login with postgresql

### ISSUE THREAD

**Issue by caosdp-rs** [codeigniter4/shield#329]
pg_query(): Query failed: ERROR:  null value in column &quot;id&quot; violates not-null constraint DETAIL:  Failing row contains (null, xxxxxxx, Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KH..., email_password, xxxx@gmail.com, null, 2022-07-29 18:42:28, 0).

---

$file | /home/xxxxx/xxxx/xxx/vendor/codeigniter4/framework/system/Database/Postgre/Connection.php
$line | 135
#4 | Array (     [sql] => INSERT INTO "auth_logins" ("ip_address", "user_agent", "id_type", "identifier", "user_id", "date", "success") VALUES ('xxxxx4', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36', 'email_password', 'xxxxx@gmail.com', NULL, '2022-07-29 18:42:28', 0)

**Comment by caosdp-rs** [comment]
Minha tabela não aceitou o autoincremento a migração foi realizada novamente e deu certo.

**Comment by kenjis** [comment]
@caosdp-rs Could you write in English?

**Comment by caosdp-rs** [comment]
this error occurred in the dump from version 11 to 9.2. Serial (AutoIncrement) is not right.
I fixed this error by redoing the migrate
