### ISSUE TITLE
Session::refreshRememberMeToken() not update row in database

### ISSUE THREAD

**Issue by jakkepedder** [codeigniter4/shield#335]
https://github.com/codeigniter4/shield/blob/7855d91908f78a0a67b6e40eb877979bd34f52ef/src/Authentication/Authenticators/Session.php#L873

Is this line correct or should it be: 
$token->hashedValidator = $this->hashValidator($validator);

**Comment by MGatner** [comment]
You are correct:
```php

class RememberModel extends Model
{
    use CheckQueryReturnTrait;

    protected $table          = 'auth_remember_tokens';
    protected $primaryKey     = 'id';
    protected $returnType     = 'object';
    protected $useSoftDeletes = false;
    protected $allowedFields  = [
        'selector',
        'hashedValidator',
        'user_id',
        'expires',
    ];
```

Good catch! Care to send a Pull Request to fix this?
