### ISSUE TITLE
Bug: Could not fin a version of package codeigniter4/shield matching your minimum-stability (stable)

### ISSUE THREAD

**Issue by gideonmkp98** [codeigniter4/shield#365]
### PHP Version

8.1.6

### CodeIgniter4 Version

4.2.3

### Shield Version

latest version

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

cli-server (PHP built-in webserver)

### Database

MySQL 8.0.28

### Did you customize Shield?

No

### What happened?

i ran the Composer require script from the readme in the Github repo. And almost directly the following message popped up in my temrinal.

![image](https://user-images.githubusercontent.com/48789974/184172797-32c5db61-4d19-4fd8-a6de-95a5c4ea567c.png)

I am running the right version of CI so i dont know what to do to fix it.

### Steps to Reproduce

Take a fresh install of CI 4.2.3 and set the database credentials right in the .env file in the project. After that run the composer require command to install the Shield package.

### Expected Output

That the package could be installed succesfully.

**Comment by datamweb** [comment]
![How to install Shield (1)](https://user-images.githubusercontent.com/9530214/184173666-efc541ba-b56c-4f2f-a7a5-d61fde7e2182.jpg)
