### ISSUE TITLE
fix: test case helper missing auth

### ISSUE THREAD

**Issue by jlopes90** [codeigniter4/shield#382]
https://github.com/codeigniter4/shield/blob/c48cb81bd80762e0133d1ba53f50e16ab99c1f6e/tests/_support/TestCase.php#L28

![imagem](https://user-images.githubusercontent.com/50026015/184634001-3e252330-d262-4eeb-88db-4bcf4e2ddd0c.png)

to

`helper(['auth', 'setting']);`

![imagem](https://user-images.githubusercontent.com/50026015/184634094-74bee622-56d9-4e29-9bfd-27367828cbbb.png)

To confirm that it is correct?

**Comment by kenjis** [comment]
Run `composer update`.

**Comment by kenjis** [comment]
@jlopes90 See #368
Now we don't need to load auth_helper and email_helper, because Composer autoloads them.
