### ISSUE TITLE
Bug: Broken register

### ISSUE THREAD

**Issue by jozefrebjak** [codeigniter4/shield#386]
### PHP Version

8.1.9

### CodeIgniter4 Version

4.2.4

### Shield Version

dev-develop

### Which operating systems have you tested for this bug?

macOS, Linux

### Which server did you use?

fpm-fcgi

### Database

MariaDB 10.8.3

### Did you customize Shield?

No

### What happened?

After updating to the latest `dev-develop` is registration of new users via `/register` route broken. It seems like no `auth_identity` is created during registration.

### Steps to Reproduce

Just follow install docs and try to register as a new user via `/register` route. We are redirected to app, but in database is no entry in `auth_identities` table.

### Expected Output

After registration of the new user create identity.

**Comment by datamweb** [comment]
@jozefrebjak, I could not reproduce!

```console
Data of Table "test__auth_identities":

+----+---------+----------------+------+--------------------+--------------------+---------+-------+-------------+--------------------+--------------------+--------------------+
| id | user_id | type           | name | secret             | secret2            | expires | extra | force_reset | last_used_at       | created_at         | updated_at         |
+----+---------+----------------+------+--------------------+--------------------+---------+-------+-------------+--------------------+--------------------+--------------------+
| 12 | 8       | email_password |      | pooya_parsa_dad... | $2y$10$u2ergbH2... |         |       | 0           | 2022-08-16 06:4... | 2022-08-16 05:3... | 2022-08-16 06:4... |
| 35 | 9       | email_password |      | jozef@yahoo.com    | $2y$10$GT.1rW0L... |         |       | 0           |                    | 2022-08-16 09:2... | 2022-08-16 09:2... |
+----+---------+----------------+------+--------------------+--------------------+---------+-------+-------------+--------------------+--------------------+--------------------+
```

**Comment by datamweb** [comment]
@jozefrebjak  I will keep this issue open for the next few days.
If you reproduce, let me know.

**Thank you for being with the team.**

**Comment by jozefrebjak** [comment]
@datamweb I already fixed the issue. I spent some time to fix it, but I think a problem was with my extended config, entity and model.

**Comment by datamweb** [comment]
Hello ,
No problem, thanks for letting us know.
