### ISSUE TITLE
Bug: $user->getEmailIdentity() returns null after saving new user

### ISSUE THREAD

**Issue by kpeu3u** [codeigniter4/shield#450]
### PHP Version

7.4

### CodeIgniter4 Version

4.2.6

### Shield Version

dev-develop

### Which operating systems have you tested for this bug?

macOS

### Which server did you use?

apache

### Database

MySQL 5.7

### Did you customize Shield?

No

### What happened?

I think something is wrong here :) Am i right?  
src/Entities/User.php

```php
/**
     * @var UserIdentity[]|null
     */
    private ?array $identities = null; **<- parameter can be either empty array**

............

/**
     * ensures that all of the user's identities are loaded
     * into the instance for faster access later.
     */
    private function populateIdentities(): void
    {
        if ($this->identities === null) { **<- check for null only, if this parameter is empty array does not get identity**
            /** @var UserIdentityModel $identityModel */
            $identityModel = model(UserIdentityModel::class);

            $this->identities = $identityModel->getIdentities($this);
        }
    }
```

### Steps to Reproduce

n/a

### Expected Output

`$user->getEmailIdentity()` to return Identity.

**Comment by kenjis** [comment]
Thank you for reporting.
I confirmed this bug.

It seems `UserModel::save()` makes `$identities` an empty array.

**Comment by kenjis** [comment]
By the way, what do you expect the user object after saving?

If you want the complete user object, you need to fetch from the database.
```php
$user = new User([ /* data */ ]);
$users->save($user);

// To get the complete user object with ID, we need to get from the database
$user = $users->findById($users->getInsertID());
```

**Comment by kenjis** [comment]
In `saveEmailIdentity()` which is called after insertion, `$this->tempUser` is the User object from the client code.

https://github.com/codeigniter4/shield/blob/9b889b351bbb424597e9f46292a3e6ce24cf71a1/src/Models/UserModel.php#L308

Getting `password_hash` calls `getPasswordHash()` and `getEmailIdentity()` and `getIdentity()` and `getIdentities()`,
and `populateIdentities()`.

https://github.com/codeigniter4/shield/blob/9b889b351bbb424597e9f46292a3e6ce24cf71a1/src/Entities/User.php#L75

And it sets `[]` to `$this->identities`.

**Comment by kenjis** [comment]
Because it is not a good idea that `save()` changes only part of the state of the object that is passed.
Is it better not to change it at all?

```diff
diff --git a/src/Entities/User.php b/src/Entities/User.php
index 41db673..648c8d4 100644
--- a/src/Entities/User.php
+++ b/src/Entities/User.php
@@ -121,6 +121,9 @@ public function createEmailIdentity(array $credentials): void
         $identityModel = model(UserIdentityModel::class);
 
         $identityModel->createEmailIdentity($this, $credentials);
+
+        // Ensure we will reload all identities
+        $this->identities = null;
     }
 
     /**
@@ -172,6 +175,9 @@ public function saveEmailIdentity(): bool
         try {
             /** @throws DataException */
             $identityModel->save($identity);
+
+            // Ensure we will reload all identities
+            $this->identities = null;
         } catch (DataException $e) {
             // There may be no data to update.
             $messages = [
diff --git a/src/Models/UserModel.php b/src/Models/UserModel.php
index ead14f0..bc804af 100644
--- a/src/Models/UserModel.php
+++ b/src/Models/UserModel.php
@@ -225,7 +225,8 @@ public function activate(User $user): void
      */
     public function insert($data = null, bool $returnID = true)
     {
-        $this->tempUser = $data instanceof User ? $data : null;
+        // Clone User for not changing the passed object.
+        $this->tempUser = $data instanceof User ? clone $data : null;
 
         $result = parent::insert($data, $returnID);
 
@@ -245,7 +246,8 @@ public function insert($data = null, bool $returnID = true)
      */
     public function update($id = null, $data = null): bool
     {
-        $this->tempUser = $data instanceof User ? $data : null;
+        // Clone User for not changing the passed object.
+        $this->tempUser = $data instanceof User ? clone $data : null;
 
         try {
             /** @throws DataException */
```

**Comment by MGatner** [comment]
Yes, that's a bad code smell for sure. I like your proposed change.

**Comment by kenjis** [comment]
@MGatner That is not enough.
I sent a PR #452

**Comment by kenjis** [comment]
@kpeu3u I sent a PR #452 
Please try if you can.

**Comment by kpeu3u** [comment]
@kenjis i agree with proposed changes but ... there is one thing

test:
use CodeIgniter\Shield\Entities\User;
......
$u = new User();

before save user:
        var_dump($u->username);
        var_dump($u->email); <- return exception depend on assert(...) at getIdentities().

maybe getIdentities() should return empty array if not $user->id in agreement with return type.

**Comment by kenjis** [comment]
@kpeu3u Why do you need to use a User object that is not fetched from the database?
It is not a complete User object. It is not recommended to use it.

**Comment by kenjis** [comment]
I've changed my mind and the PR.
See https://github.com/codeigniter4/shield/pull/452#issuecomment-1258877801

The following code throws an exception:
```php
$u = new User();

var_dump($u->username);
var_dump($u->email); // Throws LogicException: "$user->id" is null. You should not use the incomplete User object.
```
