### ISSUE TITLE
Bug: Error when running migrate at install

### ISSUE THREAD

**Issue by MarcPinnell** [codeigniter4/shield#473]
### PHP Version

8.1.4

### CodeIgniter4 Version

4.2.6

### Shield Version

Unsure how to find version

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

cli-server (PHP built-in webserver)

### Database

MariaDB

### Did you customize Shield?

No. Just getting started with install

### What happened?

Tried to run step 5 of install, migrate and got this error:
```
PHP Fatal error:  Uncaught TypeError: CodeIgniter\CLI\Console::__construct(): Argument #1 ($app) must be of type CodeIgniter\CodeIgniter, int given, called in /home/sites.local/billing.lighthouse.local/spark on line 56 and defined in /home/sites.local/billing.lighthouse.local/vendor/codeigniter4/framework/system/CLI/Console.php:29
Stack trace:
#0 /home/sites.local/billing.lighthouse.local/spark(56): CodeIgniter\CLI\Console->__construct()
#1 {main}
  thrown in /home/sites.local/billing.lighthouse.local/vendor/codeigniter4/framework/system/CLI/Console.php on line 29

```

### Steps to Reproduce

Ran this at the CL Prompt:
/usr/local/lsws/lsphp80/bin/php spark migrate --all

### Expected Output

Files should run and create DB

**Comment by kenjis** [comment]
The error has nothing to do with Shield.

Try this:
https://codeigniter4.github.io/CodeIgniter4/installation/upgrade_420.html#index-php-and-spark

**Comment by MarcPinnell** [comment]
Thanks!
