### ISSUE TITLE
Bug: if user sends 2 requests within a second CI4 Model->save() throws Error

### ISSUE THREAD

**Issue by suyovj** [codeigniter4/shield#495]
### PHP Version

8

### CodeIgniter4 Version

4.2.7

### Shield Version

 1.0.0-beta.2

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

MariaDB

### Did you customize Shield?

No

### What happened?

In Class CodeIgniter\Shield\Authentication\Authenticators\AccessTokens - Line 127

        $token->last_used_at = Time::now()->format('Y-m-d H:i:s');

Request to change the time format to 'Y-m-d H:i:s.u'

This is because, if a user sends 2 or more requests within a seconds CI4 Model->save() is throwing a 'no data to update error'

Please implement the change.

### Steps to Reproduce

Use Tokens authentications
Login using tokens
Access login check within 2 seconds

### Expected Output

No error shall be thrown

**Comment by kenjis** [comment]
Please check 1.0.0-beta.3.

**Comment by kenjis** [comment]
This bug was fixed by #376
