### ISSUE TITLE
Bug: TypeError checking permissions

### ISSUE THREAD

**Issue by virdb** [codeigniter4/shield#505]
### PHP Version

7.4.32 | 8.1.12

### CodeIgniter4 Version

4.2.8

### Shield Version

v1.0.0-beta.3

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

cli-server (PHP built-in webserver)

### Database

MariaDB 10.9.3

### Did you customize Shield?

Just disabled registration and configured groups, permissions and matrix

### What happened?

when I check for user permissions, got a Type error.

My code in controller:
```php
$user = auth()->user();
if ( $user->can('developer') || $user->can('admin.user'))
 {
   // ...
 }
```

Error:
```
TypeError
substr() expects parameter 3 to be int, bool given 
VENDORPATH/codeigniter4/shield/src/Authorization/Traits/Authorizable.php at line 259

...
259             $check = substr($permission, 0, strpos($permission, '.')) . '.*';
...
```

### Steps to Reproduce

- composer require codeigniter4/shield:v1.0.0-beta.3
- setup groups, permissions and matrix in AuthGroups.php
- add a user with appropriate permissions
- check if user has permission
- got the error

### Expected Output

expected the can() method works

**Comment by virdb** [comment]
sorry the options was not available, "Which server did you use?": php spark serve

**Comment by kenjis** [comment]
@virdb It is `cli-server (PHP built-in webserver)`. I've updated.

**Comment by kenjis** [comment]
> A permission is simply a string consisting of a scope and action, like `users.create`.
https://github.com/codeigniter4/shield/blob/develop/docs/authorization.md#defining-available-permissions

Can you show us your `$permissions`?

**Comment by virdb** [comment]
Of course,

My groups:
`public array $groups = [
        'admin' => [
            'title'       => 'Administrators',
            'description' => 'Site administrators',
        ],
        'developer' => [
            'title'       => 'Developers',
            'description' => 'Site developers',
        ],
        'user' => [
            'title'       => 'Users',
            'description' => 'Site users',
        ],
    ];`

My permissions:
`public array $permissions = [
        'admin.users'       => 'Can manage users',
        'admin.groups'      => 'Can manage groups',
        'admin.actions'     => 'Can manage actions',
        'developer'         => 'Access to all functions' 
    ];`

My matrix:
`public array $matrix = [
        'admin' => [
            'admin.*',
        ],
        'developer' => [
            'admin.*',
            'developer',
        ],
        'user' => [],
    ];`

**Comment by kenjis** [comment]
`'developer'` is not  a scope and action style like `users.create`.

**Comment by virdb** [comment]
Just tested and confirm. Thanks a lot

**Comment by kenjis** [comment]
This is misuse, but the error message is not good.
I sent a PR.
