### ISSUE TITLE
Bug: findByCredentials() returns User when email is empty string

### ISSUE THREAD

**Issue by sammyskills** [codeigniter4/shield#546]
### PHP Version

7.4

### CodeIgniter4 Version

4.2.10

### Shield Version

develop

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

MariaDB 10.4.18

### Did you customize Shield?

No.

### What happened?

`findByCredentials()` returns a valid user object when the email parameter value is empty.

### Steps to Reproduce

Do this:
```
$users = model(UserModel);
$user = $users->findByCredentials(['email' => '']);
dd($user);
```
This returns a valid `CodeIgniter\Shield\Entities\User` instance. 

### Expected Output

I expect `null` to be returned as no email address was entered in the value field.

### Anything else?

However, if I add a space with the value like so: `$user = $users->findByCredentials(['email' => ' ']);`, I get `null`.

**Comment by kenjis** [comment]
Thank you for reporting.
I sent a PR #548
