### ISSUE TITLE
Bug: unique keys on "type" and "secret" in auth_identities table breaks create user functionality in sqlite3 DB

### ISSUE THREAD

**Issue by dgvirtual** [codeigniter4/shield#552]
### PHP Version

7.4

### CodeIgniter4 Version

4.2.7

### Shield Version

1.0.0-beta.2

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

cli-server (PHP built-in webserver)

### Database

SQLite3

### Did you customize Shield?

I use it within Bonfire2, non-customized.

### What happened?

Migration code for the shield creates a table auth identities and adds unique keys on columns "type" and "secret".  It is my understanding that Codeigniter engine also creates indexes during migration on all unique columns. So, for example, in SQLite3 exported db you see this:

CREATE UNIQUE INDEX IF NOT EXISTS "auth_identities_type_secret" ON "auth_identities" (
     "type",
     "secret"
);

However, the "type" column stores non-unique values. So, again, in SQLite3 I get an error that I have described here: 

https://github.com/lonnieezell/Bonfire2/issues/218

### Steps to Reproduce

I guess it is peculiar to SQLite3 db. 

### Expected Output

Expected is creation of a new user without errors.

### Anything else?

There might also be some problem with repeated lines inserted into auth_identities for a single user (which also throws an error on the "secret" being non-unique), but that might be some issue in Bonfire. I have not investigated further.

**Comment by dgvirtual** [comment]
I am no longer sure this is a valid issue, since after update of Shield, Bonfire and Codeigniter to the latest versions today the issue no longer occurs... 

Still somebody should check if creating indexes on those columns is meaningful.

**Comment by MGatner** [comment]
I don't like them. Nothing about the table itself suggests that those should be unique, and I could imagine some identity platform with multiple secrets, some of which are not unique. 

Also, in general: I like a dumber database and smarter code. Things like unique indexes get in the way of soft deletes and data migrations. They are "nice to have" in some scenarios but in general I think they do more harm than good.

**Comment by dgvirtual** [comment]
OK, the secret column may have unique values but the type column has values in only a few categories, like "email_password". Did I understand it wrong that indexes should be created only on columns with unique values? This sql (part of exported Shield db) seems to treat both columns as unique:

` CREATE UNIQUE INDEX IF NOT EXISTS "auth_identities_type_secret" ON "auth_identities" (
 	"type",
 	"secret"
 );`

**Comment by kenjis** [comment]
What needs to be unique is "`type` + `secret`" value; if the type is different, it does not matter if the `secret` value is the same.

**Comment by dgvirtual** [comment]
Ok, I did not know about this possibility to create index on two fields... sorry for the trouble.
