### ISSUE TITLE
CLI command to manage users

### ISSUE THREAD

**Issue by robertogerola** [codeigniter4/shield#566]
Hello. I wrote a command to manage users from CLI : create, activate, deactivate, change name, change email, set password

Here my last commit :
https://github.com/robertogerola/shield/commit/ab09040c4a14c4ebbc2f3e91e3aef3b329662291

I'm still working on it. I need to add group assignment feature.
If you think it could be useful also for others I can submit a PR in the coming days.

**Comment by kenjis** [comment]
I think the command is very useful for many users.
It would be great if Shield has the command.

**Comment by lonnieezell** [comment]
I agree. I would love to see it included.

**Comment by robertogerola** [comment]
I think I fixed the mess I created with my previous PR. I wasn't able to remove the merge commits, so I created a new clean PR : #568
I'm sorry, these are my first steps with Github, I'm still learning !

**Comment by datamweb** [comment]
@robertogerola Don't worry, we've all been in the same situation as you. I guided you in #568 .
If you haven't received feedback yet, it's because of prioritization of tasks, not your performance. So go ahead.

**Comment by lonnieezell** [comment]
@robertogerola What happened to the previous PR? I'm looking forward to this command :)

**Comment by robertogerola** [comment]
@lonnieezell  Hi, my previous PR contained a lot of errors : merge commits, not signed commits, not a specific branch on my side. I removed them and create a new clean one. Hope everything is fine this time ;-)
