### ISSUE TITLE
Bug: Config $userProvider is ignored

### ISSUE THREAD

**Issue by crysaro** [codeigniter4/shield#592]
### PHP Version

8.1.13

### CodeIgniter4 Version

4.2.9

### Shield Version

v1.0.0-beta.3

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### Database

8.0.31

### Did you customize Shield?

No

### What happened?

I created a model and named it `UserModel.php` and placed it under the `/app/Models/` directory. I wanted to use this model for dealing with non auth transaction like saving user first name and last name or displaying users on a list.
I was thinking of creating another model to be used for Shield and call it `AuthModel.php`.
I left the default value for the  `$userProvider` in the `/app/Config/Auth.php` to `CodeIgniter\Shield\Models\UserModel;`

When the creating a new user using the register page this error occurs:
```
TypeError
CodeIgniter\Shield\Controllers\RegisterController::getUserProvider(): Return value must be of type CodeIgniter\Shield\Models\UserModel, App\Models\UserModel returned
```

### Steps to Reproduce

Register for a new account

### Expected Output

I am not sure if my thinking is correct but I expected Shield to still use the `CodeIgniter\Shield\Models\UserModel` which is the value of the `$userProvider` in the config  and not the `App\Models\UserModel`

**Comment by datamweb** [comment]
I haven't checked this but I'm sure you haven't considered section [user-providers](https://github.com/codeigniter4/shield/blob/develop/docs/concepts.md#user-providers).
![Screenshot 2023-01-10 171106](https://user-images.githubusercontent.com/9530214/211567719-ee1b12fc-c51d-45fc-916b-6ec06b6f6493.jpg)

If you think you have done the steps correctly, please upload the minimum code so I can check.

**Comment by datamweb** [comment]
An example of correct operation in case of setting `public string $userProvider = \App\Models\UserModel::class;`.

![demo_appmodel](https://user-images.githubusercontent.com/9530214/211632154-45491c01-956d-4c7a-87b6-8008a280b193.jpg)

**Comment by kenjis** [comment]
This is not a bug. It is the specification of CI4.
Read https://codeigniter4.github.io/CodeIgniter4/concepts/factories.html#example

**Comment by crysaro** [comment]
Thank you for the replies!
