### ISSUE TITLE
DateTime hardcoded format `Y-m-d H:i:s` drives to "Error converting data type varchar to datetime"

### ISSUE THREAD

**Issue by mikeabbott10** [codeigniter4/shield#608]
### PHP Version

8.1

### CodeIgniter4 Version

4.3

### Shield Version

1.0.0-beta3

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

SQL Server 2019

### Did you customize Shield?

No

### What happened?

My db language is Italian and expects datetime format like 'd-m-Y H:i:s'. When you attempt to login, it tries to insert a row using the format 'Y-m-d H:i:s' by default and that's hardcoded at Shield\Models\LoginModel row 71.
https://github.com/codeigniter4/shield/blob/697f570277a4d2205852cacaae4837604b1c4b88/src/Models/LoginModel.php#L71

### Steps to Reproduce

Connect to a database with a datetime expected format not equal to 'Y-m-d H:i:s' and try to login

### Expected Output

The row gets insterted

### Anything else?

I think the format has to be customizable without the need to extend the LoginModel and override the whole recordLoginAttempt just for this.

**Comment by kenjis** [comment]
Thank you for reporting.

Can SQL Server accept `YYYYY-MM-DD H:i:s` for the column? 
I believe this is standard notation.

**Comment by mikeabbott10** [comment]
Yes, it can but my company wants it to not be modified. It's standard notation for some locales, not for others

**Comment by mikeabbott10** [comment]
The title of this post should be edited. It's not about LoginModel only. It's about every datetime value insertion in db. The solution is to change the hardcoded 'Y-m-d H:i:s' string with a simple datetimeFormat constant somewhere

**Comment by kenjis** [comment]
We thought `Y-m-d H:i:s` is safe to databases regardless of locale.
So once we added `Time::toDatabase()` but removed it before the release.
https://github.com/codeigniter4/CodeIgniter4/pull/6509
https://github.com/codeigniter4/CodeIgniter4/pull/6461

> Please tell me where these kind of constants should go so i can solve this and make a PR

I'm not sure, but
1. add `Time::toDatabase()` and make it configurable with Config file for it.
2. add in `CodeIgniter\Shield\Config\Auth`.

**Comment by kenjis** [comment]
Yes, the datetime (and date only) format for database is related to data from and to database,
and all the CI4 applications. Not only for Shield.

**Comment by jozefrebjak** [comment]
@mikeabbott10 Why do you need to store datetime in different format. I'm from Europe as well and I'm using DDMMYY for a users in WEB UI and I don't have an issue at all. I'm using simple `app_date` helper function from Bonfire2  to translate datetime columns to a format as I want and it's configurable. 

I don't understand why is somebody changing language of the database or linux to the native one. I'm from Slovakia and I'm fine with default settings of DB and CodeIgniter at all.

**Comment by mikeabbott10** [comment]
> YYYY-MM-DD H:i:s is a standard. For me, it's a bad decision in your company to use something else. 

Not my decision and there's no turning back but as far as i know, since choosing a date format is legit a framework like this should also consider this possibility.

**Comment by datamweb** [comment]
> 1. add `Time::toDatabase()` and make it configurable with Config file for it.

I think this issue should be resolved in the framework, it's not just for Shield and anyone else may have this problem in their own code.

> it's a bad decision in your company to use something else.

I agree, but I don't think there should be a limit to any format. I think it doesn't matter why the user uses a different format, the important thing is the coverage of the framework and the ability to make orders, we should allow the user to have the ability to make orders.

**Comment by datamweb** [comment]
@mikeabbott10 Kenji made some changes to solve this problem, if you can check from the develop branch.

**Comment by kenjis** [comment]
To fix this issue, we need CI v4.5.0 (https://github.com/codeigniter4/CodeIgniter4/pull/8538), and Shield `develop` branch.

**Comment by datamweb** [comment]
Oh, I thought the version released today was 4.5. Sorry.

**Comment by kenjis** [comment]
@mikeabbott10 
This bug should be resolved in CI 4.5.1 and Shield 1.0.3.
