### ISSUE TITLE
Bug: Redirect on failed activation check

### ISSUE THREAD

**Issue by sammyskills** [codeigniter4/shield#630]
### PHP Version

7.4

### CodeIgniter4 Version

4.3.1

### Shield Version

develop

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

MariaDB 10.4.18

### Did you customize Shield?

No.

### What happened?

When I tried to login with the details of an inactive user, I get redirected back to the login page, with the message:
```
You must activate your account before logging in.
```
Which is normal, but it comes with the following unanswered questions:
- What next?
- What are the criteria for an active account?
- How do I go about the activation?

### Steps to Reproduce

Login using the credentials of an inactive user.

### Expected Output

I expect that the user is redirected to the account activation page, and the activation code resent to the user's email address.

### Anything else?

This bug was fixed in #391, but was no longer implemented OR overtaken by #580. See
https://github.com/codeigniter4/shield/blob/5f180c447c2e531d6c95adb700ecf26fee511573/src/Filters/SessionAuth.php#L52-L59

**Comment by datamweb** [comment]
@sammyskills Why Clouse?

**Comment by sammyskills** [comment]
Sorry, a mistake. I have reopened it again.

**Comment by kenjis** [comment]
Cannot reproduce.

```diff
--- a/app/Config/Auth.php
+++ b/app/Config/Auth.php
@@ -109,7 +109,7 @@ class Auth extends ShieldAuth
      * @var array<string, class-string<ActionInterface>|null>
      */
     public array $actions = [
-        'register' => null,
+        'register' => \CodeIgniter\Shield\Authentication\Actions\EmailActivator::class,
         'login'    => null,
     ];
 
```

Register a user.

Delete the session cookie in the browser.

Navigate to http://localhost:8080/login and Login.

Redirected to http://localhost:8080/index.php/auth/a/show, and see "We just sent an email to you with a code to confirm your email address. Copy that code and paste it below."

I get an email with activation code.

**Comment by sammyskills** [comment]
Closing this as the issue seem to have been solved in an update.
