### ISSUE TITLE
Make private properties for relations in some Entities

### ISSUE THREAD

**Issue by kenjis** [codeigniter4/shield#65]
Relations should not go in `$attributes`. it can cause a lot of confusion around what is in an Entity.

- [x] `User::$identities`
- [x] `User::$email`
- [x] `User::$password`
- [x] `User::$password_hash`
- [x] `User::$activeAccessToken`
- [x] `AccessToken::$user`

**Comment by MGatner** [comment]
Also `AccessToken::$user`. Consider `User::$email`.

**Comment by kenjis** [comment]
I made private properties in `User` entity in local repository.

**Comment by MGatner** [comment]
Good summary! Typo in "properties"

**Comment by lonnieezell** [comment]
@kenjis I believe this can be closed?
