### ISSUE TITLE
Pass class instances when available

### ISSUE THREAD

**Issue by MGatner** [codeigniter4/shield#66]
I ascribe to the "pass large" design philosophy, where you use the largest logical parameter for method input (e.g. passing `User $user` or `Authenticatable $user` instead of `string|int $userId`). This lets your validation logic remain outside the current method (I.e. you know that User exists, has a certain structure) and helps static analysis know your true intent (much less likely to pass a random string than a whole User).

I would be in favor of doing a refactor of the current models. One "CodeIgniter-specific" issue this solves is our inconsistency around Entity primary keys - sometimes int, sometimes autoincrement (natural), sometimes string (UUID or other).

**Comment by lonnieezell** [comment]
Having been using an ORM in my day job for years now, I'm in the habit of an auto-increment int as the primary key for damn near every table so didn't even think of that being an issue, honestly. 

I'm not opposed to this, and frequently do the same thing. However, I don't know that I have the energy to take a pass at that currently. Looking at our interfaces there's nothing that would stop us from doing that change after the initial release if someone feels strongly enough to tackle that.

**Comment by MGatner** [comment]
I can make time to do a pass at it, I just wanted buy-in before I spent time one something that nobody else wanted. Let's wait for #44 first so we have a better baseline (and so poor @kenjis doesn't have to rebase it yet again).

**Comment by MGatner** [comment]
Re: autoincrement, yes I'm totally guilty as well. The only project I can think of where I used string primaries is my NoSQL (Firebase) context where you can't use autoincrementals - that was actually what got me to start switching my packages over to support string primaries.

**Comment by lonnieezell** [comment]
I don't see this change being made prior to a release. Closing. If we decide strongly on this it can be a new major release.

**Comment by MGatner** [comment]
I still think this might be worth having. I will find some time to work up a first attempt so we can see what it would look like at least...

**Comment by kenjis** [comment]
This is an Auth package and all classes are tightly coupled with the User object.
So I think this change is okay.
