### ISSUE TITLE
Bug: Getting logged out after reload

### ISSUE THREAD

**Issue by OnyxException** [codeigniter4/shield#702]
### PHP Version

8.1.12

### CodeIgniter4 Version

4.2.7

### Shield Version

dev-develop

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

cli-server (PHP built-in webserver)

### Database

MySQL

### Did you customize Shield?

Yes, changed in shield/src/Auth.php this:  `$routes->group('/', ...`
to:  `$routes->group('/auth/', ....`

### What happened?

If I login via /auth/login, I get on my Landing Page, there I made this:
```php
<?php $auth = service('auth'); ?>
<h6 class="dropdown-header">
  <?= auth()->loggedIn() ? 'Hallo, ' . auth()->user()->username : 'Dein Profil' ?>
</h6>
```

Everythings great after I directly get there, I get "Hello OnyxException", but if I reload the page, I am not logged in anymore

### Steps to Reproduce

Reload the page, Ig

### Expected Output

I just want to be still logged in.

### Anything else?

So, the ci_session cookie is still the same, the Session Settings are correctly, as I know.

**Comment by kenjis** [comment]
Cannot reproduce.

**Comment by datamweb** [comment]
@OnyxException Unfortunately, we could not reproduce your problem. And considering the lack of feedback from you, we consider this issue to be resolved.

Class **shield/src/Auth.php** is part of the main file Shield and you should not make any changes in it. This is bad practice. If you need to change the default routes, apply these changes in **Config/Routes.php**.

Feel free to reopen the issue if your problem still exists, providing more details to reproduce the error.

**Comment by hafidzcrunchy** [comment]
I thought you insert the code `<li class="menu-item hidden"><a href="<?php auth()->logout(); ?>">Logout</a></li>` in the welcome_message.php file like me before. It's make logged out automatically. So remove it, and gotcha it will be fine!

> ### PHP Version
> 8.1.12
> 
> ### CodeIgniter4 Version
> 4.2.7
> 
> ### Shield Version
> dev-develop
> 
> ### Which operating systems have you tested for this bug?
> Windows
> 
> ### Which server did you use?
> cli-server (PHP built-in webserver)
> 
> ### Database
> MySQL
> 
> ### Did you customize Shield?
> Yes, changed in shield/src/Auth.php this: `$routes->group('/', ...` to: `$routes->group('/auth/', ....`
> 
> ### What happened?
> If I login via /auth/login, I get on my Landing Page, there I made this:
> 
> ```
> <?php $auth = service('auth'); ?>
> <h6 class="dropdown-header">
>   <?= auth()->loggedIn() ? 'Hallo, ' . auth()->user()->username : 'Dein Profil' ?>
> </h6>
> ```
> 
> Everythings great after I directly get there, I get "Hello OnyxException", but if I reload the page, I am not logged in anymore
> 
> ### Steps to Reproduce
> Reload the page, Ig
> 
> ### Expected Output
> I just want to be still logged in.
> 
> ### Anything else?
> So, the ci_session cookie is still the same, the Session Settings are correctly, as I know.
