### ISSUE TITLE
Problem with route configuration

### ISSUE THREAD

**Issue by Sammyskills** [codeigniter4/shield#72]
Hi,

I have been able to setup this package in my CI4 project to an extent, but I'm having issues with the routes configuration. 

From the [docs](https://github.com/lonnieezell/codeigniter-shield/blob/develop/docs/0%20-%20install.md#route-configuration) _(which doesn't explain much unfortunately)_, it states
`If you need to customize how any of the auth features are handled, you will likely need to update the routes to point to the correct controllers. You can still use the auth()->routes() helper, but you need to pass a list of routes to an except option:`
`auth()->routes($routes, ['except' => ['login', 'register']]);`

I have tried adding this in my App/Config/Routes.php file, but it returned an error: `Call to undefined function Config\auth()`.

I have already extended the controllers in my App/Controllers, but I don't know how to update the route to point to the new controllers.

Please help.

**Comment by kenjis** [comment]
```php
service('auth')->routes($routes, ['except' => ['login', 'register']]);
```

**Comment by Sammyskills** [comment]
Thanks for the reply.

But that does solve my primary issue. 

Please how do I state the new controllers to be used ?

**Comment by kenjis** [comment]
Add routes you want like you always add routes.
See https://codeigniter4.github.io/userguide/incoming/routing.html

**Comment by Sammyskills** [comment]
Tried this also, but the routes are still pointing to the default routes.

**Comment by lonnieezell** [comment]
Here's an example taken from Bonfire: 

```php
// Auth routes
$routes->get('register', '\App\Controllers\Auth\RegisterController::registerView');
$routes->get('login', '\App\Controllers\Auth\LoginController::loginView');
$routes->get('login/magic-link', '\App\Controllers\Auth\MagicLinkController::loginView', ['as' => 'magic-link']);
$routes->post('login/magic-link', '\App\Controllers\Auth\MagicLinkController::loginAction');
$routes->get('login/verify-magic-link', '\App\Controllers\Auth\MagicLinkController::verify', ['as' => 'verify-magic-link']);
service('auth')->routes($routes, ['except' => ['login', 'register']]);
```

**Comment by Sammyskills** [comment]
Thanks @lonnieezell .

Oh, I see where the problem was. I put the new route declarations below the 'service('auth')->routes()'.

But I was even expecting that after adding the `except` tag in the route definition, the excluded routes should return a 404 page. That didn't happen.

Is that a bug or an intended behaviour ?

The reason I asked is because using the except keyword in resource controllers/presenter removes the route entirely (AFAIK).

**Comment by kenjis** [comment]
@Sammyskills It seems a bug. 

Please try:
```diff
--- a/src/Auth.php
+++ b/src/Auth.php
@@ -110,7 +110,7 @@ public function routes(RouteCollection &$routes, array $config = [])
 
         $routes->group('/', ['namespace' => 'Sparks\Shield\Controllers'], static function ($routes) use ($authRoutes, $config) {
             foreach ($authRoutes as $name => $row) {
-                if (! isset($config['except']) || (isset($config['except']) && ! array_key_exists($name, $config['except']))) {
+                if (! isset($config['except']) || (isset($config['except']) && ! in_array($name, $config['except'], true))) {
                     foreach ($row as $params) {
                         $options = isset($params[3])
                             ? ['as' => $params[3]]
```
