### ISSUE TITLE
Bug: Typo in JWT docs

### ISSUE THREAD

**Issue by AndrewDFrazier-SwofMedia** [codeigniter4/shield#731]
### PHP Version

8.1.1

### CodeIgniter4 Version

4.3.4

### Shield Version

v1.0.0-beta.6

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

MySQL 8

### Did you customize Shield?

Yes; used the sample controller from JWT docs: docs/addons/jwt.md

### What happened?

There's a typo causing a crash:  in the line 'rules'  => 'required|' . Passwords::getMaxLenghtRule(),

The error is Call to undefined method CodeIgniter\Shield\Authentication\Passwords::getMaxLenghtRule()

the line should read Passwords::getMaxLengthRule()

### Steps to Reproduce

Try using the sample controller

### Expected Output

I expect a JWT token to be returned.

**Comment by datamweb** [comment]
@AndrewDFrazier-SwofMedia Thanks for your report, I have sent PR #732.
