### ISSUE TITLE
Dev: error phpstan

### ISSUE THREAD

**Issue by datamweb** [codeigniter4/shield#738]
The new version settings [v2.1.1] has been released. This problem started from version[ 2.1.1](https://github.com/codeigniter4/settings).

```console
Error: Cannot call method forget() on array|bool|float|int|object|string|void.
 ------ ------------------------------------------------------------------ 
  Line   tests/Authentication/Authenticators/SessionAuthenticatorTest.php  
 ------ ------------------------------------------------------------------ 
  112    Cannot call method forget() on                                    
         array|bool|float|int|object|string|void.                          
 ------ ------------------------------------------------------------------ 
```
see https://github.com/codeigniter4/shield/actions/runs/4960040688/jobs/8876233138?pr=736

**Temporary solution:**

```diff
-setting()->forget('Cookie.prefix');
+service('settings')->forget('Cookie.prefix');

```

https://github.com/codeigniter4/shield/blob/812338879b0ebabdc1c46e5fae7b2f429aa70005/tests/Authentication/Authenticators/SessionAuthenticatorTest.php#L82-L113

**Comment by kenjis** [comment]
Sent PR to fix too sketchy `@return`.
https://github.com/codeigniter4/settings/pull/78
