### ISSUE TITLE
Bug: Database exceptions "Specified key was too long; max key length is 1000 bytes"

### ISSUE THREAD

**Issue by kpeu3u** [codeigniter4/shield#741]
### PHP Version

7.4

### CodeIgniter4 Version

4.3.4

### Shield Version

develop

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### Database

MariaDB 10.6.13

### Did you customize Shield?

no

### What happened?

If deploy to shared hosting and MySQL default_storage_engine is set to MyISAM there is no possibility to change it to InnoDB, spark migrate --all return Exceptions
 
```console
CodeIgniter v4.3.4 Command Line Tool - Server Time: 2023-05-14 15:46:19 UTC+00:00

Running all new migrations...

[CodeIgniter\Database\Exceptions\DatabaseException]

Specified key was too long; max key length is 1000 bytes

at SYSTEMPATH/Database/BaseConnection.php:646
```

### Steps to Reproduce

run `spark migrate --all` return on MySQL server configured with default_storage_engine=MyISAM

### Expected Output

Migrations complete without error.

### Anything else?

It is a good to have `['ENGINE' => 'InnoDB']` set as an attribute in createTable methods for tables that uses Foreign key or to all methods.

**Comment by kenjis** [comment]
It is documented.
See https://codeigniter4.github.io/shield/install/#note-migration-error

**Comment by datamweb** [comment]
As Kenjis pointed out, we don't consider this a bug.

However, I agree to make changes to the migration file. Can you sent PR?

**Comment by kpeu3u** [comment]
@kenjis It is documented but in some cases someones have no superadmin or admin access on shared hosting servers and default_storage_engine can NOT be changed!

**Comment by kenjis** [comment]
@kpeu3u That's too bad. If the default storage engine is MyISAM, it is out of dated.
But I understand that if you use such servers, you need `['ENGINE' => 'InnoDB']`.

Shield does not support MyISAM, and almost uses use InnoDB. So I'm fine to add `['ENGINE' => 'InnoDB']` to the migration file when using MySQL.

Can you send a PR for it?

**Comment by kpeu3u** [comment]
I have sent PR [#745](https://github.com/codeigniter4/shield/pull/745), those changes also can be moved in Auth config.

**Comment by datamweb** [comment]
> can be moved in Auth config.

I don't see any need for this.

**Comment by gridphp** [comment]
I am still getting this error, installed latest build.

CodeIgniter v4.5.1 Command Line Tool - Server Time: 2024-04-17 07:44:23 UTC+00:00

Running all new migrations...
[CodeIgniter\Database\Exceptions\DatabaseException]
Specified key was too long; max key length is 767 bytes
at SYSTEMPATH\Database\BaseConnection.php:676

I verified that this line exist in migration file.

        $this->attributes = ($this->db->getPlatform() === 'MySQLi') ? ['ENGINE' => 'InnoDB'] : [];

Plus, i've also removed the test migration file as in note.

**Comment by datamweb** [comment]
@gridphp  If you are sure you are using the Shield latest version, please create a new issue and explain **how we can reproduce your problem.**
