### ISSUE TITLE
Dev: remove supportOldDangerousPassword before v1.0.0 release

### ISSUE THREAD

**Issue by kenjis** [codeigniter4/shield#771]
See https://github.com/codeigniter4/shield/blob/develop/UPGRADING.md#if-you-want-to-allow-login-with-existing-passwords

https://github.com/codeigniter4/shield/blob/0bf28b24e6f2e7954e67cb686ce214d639812113/src/Config/Auth.php#L377-L385

**Comment by omerimzali** [comment]
@kenjis I sent a PR for the issue.
