### ISSUE TITLE
Bug: controller run even if $allowMagicLinkLogins is false

### ISSUE THREAD

**Issue by mshannaq** [codeigniter4/shield#777]
### PHP Version

8.2.7

### CodeIgniter4 Version

4.3.7

### Shield Version

dev-develop

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### Database

MySQl 8.0

### Did you customize Shield?

if you use direct link
http://localhost/login/magic-link
even if $allowMagicLinkLogins set to false in Config/Auth.php
the view form magic-link-login '\CodeIgniter\Shield\Views\magic_link_form' will be shown. and if the form submitted the email will be sent

### What happened?

disable magic link $allowMagicLinkLogins  = false in Config/Auth.php
goto http://localhost/login/magic-link directly

### Steps to Reproduce

disable magic link $allowMagicLinkLogins  = false in Config/Auth.php
goto http://localhost/login/magic-link directly

### Expected Output

not to show the form while allowMagicLinkLogins  = false

**Comment by datamweb** [comment]
Hello @mshannaq , thanks for your report.
I sent PR #778.

**Comment by kenjis** [comment]
@mshannaq Thank you for reporting. I've confirmed the bug.
