### ISSUE TITLE
strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated

### ISSUE THREAD

**Issue by kenjis** [codeigniter4/shield#83]
```
There was 1 error:

1) Tests\Controllers\ActionsTest::testEmailActivateShow
ErrorException: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated

/home/runner/work/shield/shield/vendor/codeigniter4/framework/system/Email/Email.php:728
/home/runner/work/shield/shield/vendor/codeigniter4/framework/system/Email/Email.php:541
/home/runner/work/shield/shield/src/Authentication/Actions/EmailActivator.php:44
/home/runner/work/shield/shield/src/Controllers/ActionController.php:54
/home/runner/work/shield/shield/src/Controllers/ActionController.php:42
/home/runner/work/shield/shield/vendor/codeigniter4/framework/system/CodeIgniter.php:830
/home/runner/work/shield/shield/vendor/codeigniter4/framework/system/CodeIgniter.php:419
/home/runner/work/shield/shield/vendor/codeigniter4/framework/system/CodeIgniter.php:326
/home/runner/work/shield/shield/vendor/codeigniter4/framework/system/Test/FeatureTestTrait.php:188
/home/runner/work/shield/shield/vendor/codeigniter4/framework/system/Test/FeatureTestTrait.php:222
/home/runner/work/shield/shield/tests/Controllers/ActionsTest.php:215
```
https://github.com/codeigniter4/shield/runs/6204722220?check_suite_focus=true

**Comment by kenjis** [comment]
This is because `$user->getAuthEmail()` returns null.
https://github.com/codeigniter4/shield/blob/0e642cf2050401e1d3b088dc862b6f5babd26ea1/src/Authentication/Actions/EmailActivator.php#L44

**Comment by MGatner** [comment]
I solved this parallel issue on Myth:Auth by setting an attribute cast on `User`. We should decide if emails are actually "strongly required" and either adjust the interface or add the cast (or both).

**Comment by MGatner** [comment]
Looks like we do intentionally support `null` so we'll have to check for a valid email before activating this. 

@lonnieezell I gotta say having the interface and trait named the same can be terribly confusing every time I go digging for methods.

**Comment by kenjis** [comment]
I think email in `User` should be optional.
There are use cases which do not use email.

**Comment by kenjis** [comment]
> the interface and trait named the same can be terribly confusing every time I go digging for methods.

I agree.
