### ISSUE TITLE
problem with email_2fa

### ISSUE THREAD

**Issue by adnduweb** [codeigniter4/shield#84]
Hi

![Screenshot at Apr 28 21-40-16](https://user-images.githubusercontent.com/34213953/165832938-38be9449-75a8-4e5a-ac6d-35cf2f013da9.png)

I am working on two-factor validation and I have a problem. 
When I log in, I am redirected to the "auth/a/handle" page but when I enter my email the "getAuthEmail()" method does not find me and returns "null"

Do you have an idea?

**Comment by jozefrebjak** [comment]
@adnduweb  definitely it's because of the `getAuthEmail()`. trait `Authenticatable has function 

```php
    /**
     * Returns the email address for this user.
     *
     * @return string|null
     */
    public function getAuthEmail()
    {
        $column = $this->getAuthEmailColumn();

        return $this->{$column} ?? null;
    }
```

and getAuthEmailColumn()

```php
    /**
     * Returns the name of the column with the
     * email address of this user.
     */
    public function getAuthEmailColumn(): string
    {
        return 'email';
    }
```

but there is no column email within users table. @kenjis  ? Was this tested because all calls to $this->getAuthEmail are now working at all.

**Comment by kenjis** [comment]
I think there are a few bugs around properties in `User` that are not in `user` table.
We are discussing interfaces of this library now.

**Comment by Sammyskills** [comment]
I think we can use the `UserProvider` to retrieve the user's details, just like it is in the MagicController file. Something like this since we already have the user id:

`$user = $this->provider->findbyCredentials(['id' => $user->getAuthId()])`

**Comment by Sammyskills** [comment]
Using `$user->email` works. 

I just tested it now.

**Comment by lonnieezell** [comment]
I made a PR that's under discussion: #94

**Comment by kenjis** [comment]
I believe this was fixed in the latest `develop`.
