### ISSUE TITLE
Bug: Bad redirection in the registration process (auth/a/show and auth/a/verify)

### ISSUE THREAD

**Issue by ms1495** [codeigniter4/shield#879]
### PHP Version

8.2.10

### CodeIgniter4 Version

4.4.1

### Shield Version

1.0.0-beta.6

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

MariaDB 11.1

### Did you customize Shield?

No

### What happened?

When the shield routes are defined as following:
```php
  $routes->group('{locale}/account', static function($routes) {
    service('auth')->routes($routes);
  });
```
some URLS are not generated correctly in the registration process:
* https://glossary.local/glossary/auth/a/show instead of https://glossary.local/glossary/fr/account/auth/a/show
* https://glossary.local/glossary/auth/a/verify instead of https://glossary.local/glossary/fr/account/auth/a/verify

### Steps to Reproduce

1. Rewrite the shield routes to include locale and a top level
2. Try to register a new user

### Expected Output

Correct redirection and form submitted to the right URL.

### Anything else?

A possible solution is to make a fix in two files:
* In Controllers\RegistrerController.php:
change: return redirect()->to('auth/a/show');
into:      return redirect()->route('auth-action-show');
* In Views\email_activate_show.php
change: &lt;form action="&lt;?= site_url('auth/a/verify') ?&gt;" method="post"&gt;
into:      &lt;form action="&lt;?= url_to('auth-action-verify') ?&gt;" method="post"&gt;

**Comment by kenjis** [comment]
Thank you! You are correct.

**Comment by sammyskills** [comment]
Thank you for reporting, @ms1495.

I actually saw that in my previous PR and had it in mind to send a PR, but it skipped my memory again 🤦‍♂️.

I've sent a PR #883.
