### ISSUE TITLE
Bug: CodeIgniter\Shield\Authentication\Authenticators\setting()

### ISSUE THREAD

**Issue by exquisiteboy** [codeigniter4/shield#928]
### PHP Version

8.0.30

### CodeIgniter4 Version

4.3.5

### Shield Version

dev-develop

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

fpm-fcgi

### Database

MYSQL

### Did you customize Shield?

NO

### What happened?

everything was working fine just updated the code and package updated and everything gone wrong

### Steps to Reproduce

add the filter check for the login status and then the exception is thrown for the undefined method of setting although the library is there

### Expected Output

should be working fine with the login  as settings library is installed and there but the shield couldn't find

**Comment by kenjis** [comment]
See https://github.com/codeigniter4/shield/blob/develop/UPGRADING.md#version-100-beta6-to-100-beta7
