### ISSUE TITLE
Bug: Does not appear to work with MS SQL

### ISSUE THREAD

**Issue by ollieonline** [codeigniter4/shield#939]
### PHP Version

8.2.12

### CodeIgniter4 Version

4.2.2

### Shield Version

v1.0.0-beta.7

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

cli-server (PHP built-in webserver)

### Database

MS SQL Server 2019

### Did you customize Shield?

No, no customisations made.

### What happened?

Started with a fresh code igniter installation and connected successfully to a Microsoft SQL Database, connection works and tested ok. Then installed (using composer) Shield. As Soon as installed Shield getting error messages:

```
Unable to connect to the database.
Main connection [sqlsrv]: [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: No connection could be made because the target machine actively refused it.
SQLSTATE: 08001, code: 10061
[Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired SQLSTATE: HYT00, code: 0
[Microsoft][ODBC Driver 17 for SQL Server]A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online. SQLSTATE: 08001, code: 10061 
```

SQL server detailed are correct despite the error message. As soon as shield is removed the site begins to function again.

### Steps to Reproduce

Install Shield with a fresh code igniter install and connect to a SQL server database.

### Expected Output

Expecting to see the product work correct.

**Comment by kenjis** [comment]
Shield does not supprot CodeIgniter 4.2.2.
