### ISSUE TITLE
Bug: User()->syncPermissions() throwing error

### ISSUE THREAD

**Issue by christen90** [codeigniter4/shield#971]
### PHP Version

8.1.3

### CodeIgniter4 Version

4.3.8

### Shield Version

v1.0.0-beta.8

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

cgi-fcgi

### Database

MariaDB 10.10

### Did you customize Shield?

Yes - added authentification via RemoteUser from IIS (Windows Authentification)

### What happened?

In a script user permissions are synchronized with LDAP groups. Beta.7 worked Beta.8 throws error during call of _syncPermissions_.

[Error]

Call to undefined function CodeIgniter\Shield\Authorization\Traits\setting()

at VENDORPATH\codeigniter4\shield\src\Authorization\Traits\Authorizable.php:414

Backtrace:
  1    VENDORPATH\codeigniter4\shield\src\Authorization\Traits\Authorizable.php:208
       CodeIgniter\Shield\Entities\User()->getConfigPermissions()

  2    ROOTPATH\libs\sync_ldap_groups.php:216
       CodeIgniter\Shield\Entities\User()->syncPermissions()
...

### Steps to Reproduce

1. $shield_user = $users->findById(1);
    $permissions = ['read', 'write'];
2. call_user_func_array(array($shield_user, "syncPermissions"), $permissions);

### Expected Output

no error thrown

**Comment by kenjis** [comment]
This is not a bug. You just did not follow the Upgrade Guide.

**Comment by christen90** [comment]
Thanks for really quick support (just within 10 minutes - 🎉).
modifieing the config mentioned in [Section helper-autoloading](https://github.com/codeigniter4/shield/blob/develop/UPGRADING.md#helper-autoloading) did the trick.

Sorry for bothering you but at least others can find a solution when searching for error message now.

BR christen90

**Comment by kenjis** [comment]
No problem! Nobody's perfect.
