### ISSUE TITLE
Bug: Cannot POST /index.php/register when doing register

### ISSUE THREAD

**Issue by ignutanz** [codeigniter4/shield#994]
### PHP Version

8.2.7

### CodeIgniter4 Version

4.4.3

### Shield Version

1.0

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### Database

MySQL

### Did you customize Shield?

No

### What happened?

when i tried to do register and after entering the info i click register. I get the error:
`Cannot POST /index.php/register`

### Steps to Reproduce

Go to Register, Input details and click register.

### Expected Output

Redirect to Login form after storing data in DB

### Anything else?

none

**Comment by kenjis** [comment]
Cannot reproduce.
Try this: https://github.com/kenjis/ci4-shield-test

**Comment by kenjis** [comment]
No feedback. Close.
