### ISSUE TITLE
Bug: Error in \vendor\codeigniter4\shield\src\Auth.php

### ISSUE THREAD

**Issue by budialok** [codeigniter4/shield#997]
### PHP Version

8.2

### CodeIgniter4 Version

4.4

### Shield Version

1.0.0

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

MySQL

### Did you customize Shield?

I only replace your default login view to my own custom

### What happened?

We found syntax error in file \vendor\codeigniter4\shield\src\Auth.php in following line:

1) Line 139 generate syntax error 'Undefined property '$routes'.' in following code: 
     $authRoutes = config('AuthRoutes')->routes;  
2) Line 191 generate runtime error in following code:
     return $authenticator->{$method}(...$args);

### Steps to Reproduce

I was doing the debugging process and found above two errors i haave mentioned

### Expected Output

App should be running well without any error

**Comment by datamweb** [comment]
Hi, welcome.
I don't see any problem now.

Your description is not sufficient to reproduce the error. Please provide step-by-step steps to reproduce the error.

![Screenshot 2024-01-08 060033](https://github.com/codeigniter4/shield/assets/9530214/7f89226c-8881-47e2-a17c-bcd3ef95f7f7)

**Comment by budialok** [comment]
The problem was NOT showing up on login form above.

It is coming from when I call function Check() from service('Auth'), was called in controller and it end up showing error in causing module \vendor\codeigniter4\shield\src\Auth.php line 191.

This is the thrown error from debugging console:
"Too few arguments to function CodeIgniter\Shield\Authentication\Authenticators\Session::check(), 0 passed in C:\xampp\htdocs\klikruma.com\vendor\codeigniter4\shield\src\Auth.php on line 191 and exactly 1 expected"

For your info

![image](https://github.com/codeigniter4/shield/assets/48044948/2696c42e-9e0c-4fd0-ba28-d539c14ec076)
